/* tslint:disable */
/* eslint-disable */
/**
 * Product API
 * API to retrieve and create product information
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface CreateProductRequest
 */
export interface CreateProductRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequest
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof CreateProductRequest
     */
    'price': number;
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequest
     */
    'observation'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequest
     */
    'expiresAt'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateProductRequest
     */
    'taxes'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateProductRequest
     */
    'discounts'?: Array<string>;
}
/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponse
     */
    'error'?: string;
    /**
     * 
     * @type {number}
     * @memberof ErrorResponse
     */
    'code'?: number;
}
/**
 * 
 * @export
 * @interface GetAllProductsPaginatedResponse
 */
export interface GetAllProductsPaginatedResponse {
    /**
     * 
     * @type {Pagination}
     * @memberof GetAllProductsPaginatedResponse
     */
    'pagination'?: Pagination;
    /**
     * 
     * @type {Array<ProductResponse>}
     * @memberof GetAllProductsPaginatedResponse
     */
    'data'?: Array<ProductResponse>;
}
/**
 * 
 * @export
 * @interface Pagination
 */
export interface Pagination {
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'totalItems'?: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'pageSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'currentPage'?: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'totalPages'?: number;
}
/**
 * 
 * @export
 * @interface ProductResponse
 */
export interface ProductResponse {
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    'reference'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductResponse
     */
    'price'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    'observation'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    'expiresAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    'createdAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductResponse
     */
    'taxes'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductResponse
     */
    'descount'?: number;
}
/**
 * 
 * @export
 * @interface UpdateProductRequest
 */
export interface UpdateProductRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductRequest
     */
    'price'?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'observation'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'expiresAt'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateProductRequest
     */
    'taxes'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateProductRequest
     */
    'discounts'?: Array<string>;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new product
         * @param {CreateProductRequest} createProductRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProduct: async (createProductRequest: CreateProductRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createProductRequest' is not null or undefined
            assertParamExists('createProduct', 'createProductRequest', createProductRequest)
            const localVarPath = `/api/v1/products`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createProductRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a product by ID
         * @param {string} id Unique identifier of the product to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProduct: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteProduct', 'id', id)
            const localVarPath = `/api/v1/products/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieve a list of products
         * @param {number} [from] The starting index of the products.
         * @param {number} [size] The number of products to return.
         * @param {string} [filter] Filter criteria for products.
         * @param {GetAllProductsOrderByEnum} [orderBy] Field to order products by.
         * @param {GetAllProductsDirectionEnum} [direction] Sorting direction.
         * @param {GetAllProductsStatusEnum} [status] Filter product by their status.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllProducts: async (from?: number, size?: number, filter?: string, orderBy?: GetAllProductsOrderByEnum, direction?: GetAllProductsDirectionEnum, status?: GetAllProductsStatusEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/products`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (from !== undefined) {
                localVarQueryParameter['from'] = from;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['orderBy'] = orderBy;
            }

            if (direction !== undefined) {
                localVarQueryParameter['direction'] = direction;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Partially update a product
         * @param {string} id The ID of the product to update
         * @param {UpdateProductRequest} updateProductRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProductPartially: async (id: string, updateProductRequest: UpdateProductRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateProductPartially', 'id', id)
            // verify required parameter 'updateProductRequest' is not null or undefined
            assertParamExists('updateProductPartially', 'updateProductRequest', updateProductRequest)
            const localVarPath = `/api/v1/products/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateProductRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new product
         * @param {CreateProductRequest} createProductRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createProduct(createProductRequest: CreateProductRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProductResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createProduct(createProductRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createProduct']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a product by ID
         * @param {string} id Unique identifier of the product to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteProduct(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteProduct(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteProduct']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retrieve a list of products
         * @param {number} [from] The starting index of the products.
         * @param {number} [size] The number of products to return.
         * @param {string} [filter] Filter criteria for products.
         * @param {GetAllProductsOrderByEnum} [orderBy] Field to order products by.
         * @param {GetAllProductsDirectionEnum} [direction] Sorting direction.
         * @param {GetAllProductsStatusEnum} [status] Filter product by their status.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllProducts(from?: number, size?: number, filter?: string, orderBy?: GetAllProductsOrderByEnum, direction?: GetAllProductsDirectionEnum, status?: GetAllProductsStatusEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAllProductsPaginatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllProducts(from, size, filter, orderBy, direction, status, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getAllProducts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Partially update a product
         * @param {string} id The ID of the product to update
         * @param {UpdateProductRequest} updateProductRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateProductPartially(id: string, updateProductRequest: UpdateProductRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProductResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateProductPartially(id, updateProductRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateProductPartially']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new product
         * @param {DefaultApiCreateProductRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProduct(requestParameters: DefaultApiCreateProductRequest, options?: RawAxiosRequestConfig): AxiosPromise<ProductResponse> {
            return localVarFp.createProduct(requestParameters.createProductRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a product by ID
         * @param {DefaultApiDeleteProductRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProduct(requestParameters: DefaultApiDeleteProductRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteProduct(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieve a list of products
         * @param {DefaultApiGetAllProductsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllProducts(requestParameters: DefaultApiGetAllProductsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<GetAllProductsPaginatedResponse> {
            return localVarFp.getAllProducts(requestParameters.from, requestParameters.size, requestParameters.filter, requestParameters.orderBy, requestParameters.direction, requestParameters.status, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Partially update a product
         * @param {DefaultApiUpdateProductPartiallyRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProductPartially(requestParameters: DefaultApiUpdateProductPartiallyRequest, options?: RawAxiosRequestConfig): AxiosPromise<ProductResponse> {
            return localVarFp.updateProductPartially(requestParameters.id, requestParameters.updateProductRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createProduct operation in DefaultApi.
 * @export
 * @interface DefaultApiCreateProductRequest
 */
export interface DefaultApiCreateProductRequest {
    /**
     * 
     * @type {CreateProductRequest}
     * @memberof DefaultApiCreateProduct
     */
    readonly createProductRequest: CreateProductRequest
}

/**
 * Request parameters for deleteProduct operation in DefaultApi.
 * @export
 * @interface DefaultApiDeleteProductRequest
 */
export interface DefaultApiDeleteProductRequest {
    /**
     * Unique identifier of the product to delete
     * @type {string}
     * @memberof DefaultApiDeleteProduct
     */
    readonly id: string
}

/**
 * Request parameters for getAllProducts operation in DefaultApi.
 * @export
 * @interface DefaultApiGetAllProductsRequest
 */
export interface DefaultApiGetAllProductsRequest {
    /**
     * The starting index of the products.
     * @type {number}
     * @memberof DefaultApiGetAllProducts
     */
    readonly from?: number

    /**
     * The number of products to return.
     * @type {number}
     * @memberof DefaultApiGetAllProducts
     */
    readonly size?: number

    /**
     * Filter criteria for products.
     * @type {string}
     * @memberof DefaultApiGetAllProducts
     */
    readonly filter?: string

    /**
     * Field to order products by.
     * @type {'createdAt'}
     * @memberof DefaultApiGetAllProducts
     */
    readonly orderBy?: GetAllProductsOrderByEnum

    /**
     * Sorting direction.
     * @type {'ASC' | 'DESC'}
     * @memberof DefaultApiGetAllProducts
     */
    readonly direction?: GetAllProductsDirectionEnum

    /**
     * Filter product by their status.
     * @type {'ACTIVE' | 'INACTIVE'}
     * @memberof DefaultApiGetAllProducts
     */
    readonly status?: GetAllProductsStatusEnum
}

/**
 * Request parameters for updateProductPartially operation in DefaultApi.
 * @export
 * @interface DefaultApiUpdateProductPartiallyRequest
 */
export interface DefaultApiUpdateProductPartiallyRequest {
    /**
     * The ID of the product to update
     * @type {string}
     * @memberof DefaultApiUpdateProductPartially
     */
    readonly id: string

    /**
     * 
     * @type {UpdateProductRequest}
     * @memberof DefaultApiUpdateProductPartially
     */
    readonly updateProductRequest: UpdateProductRequest
}

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Create a new product
     * @param {DefaultApiCreateProductRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createProduct(requestParameters: DefaultApiCreateProductRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createProduct(requestParameters.createProductRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a product by ID
     * @param {DefaultApiDeleteProductRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deleteProduct(requestParameters: DefaultApiDeleteProductRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteProduct(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieve a list of products
     * @param {DefaultApiGetAllProductsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getAllProducts(requestParameters: DefaultApiGetAllProductsRequest = {}, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getAllProducts(requestParameters.from, requestParameters.size, requestParameters.filter, requestParameters.orderBy, requestParameters.direction, requestParameters.status, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Partially update a product
     * @param {DefaultApiUpdateProductPartiallyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public updateProductPartially(requestParameters: DefaultApiUpdateProductPartiallyRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateProductPartially(requestParameters.id, requestParameters.updateProductRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const GetAllProductsOrderByEnum = {
    CreatedAt: 'createdAt'
} as const;
export type GetAllProductsOrderByEnum = typeof GetAllProductsOrderByEnum[keyof typeof GetAllProductsOrderByEnum];
/**
 * @export
 */
export const GetAllProductsDirectionEnum = {
    Asc: 'ASC',
    Desc: 'DESC'
} as const;
export type GetAllProductsDirectionEnum = typeof GetAllProductsDirectionEnum[keyof typeof GetAllProductsDirectionEnum];
/**
 * @export
 */
export const GetAllProductsStatusEnum = {
    Active: 'ACTIVE',
    Inactive: 'INACTIVE'
} as const;
export type GetAllProductsStatusEnum = typeof GetAllProductsStatusEnum[keyof typeof GetAllProductsStatusEnum];


