/* tslint:disable */
/* eslint-disable */
/**
 * Unit API
 * API to manage measurement units used for product pricing.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface CreateUnitRequest
 */
export interface CreateUnitRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateUnitRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CreateUnitRequest
     */
    'abbreviation': string;
}
/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponse
     */
    'error'?: string;
    /**
     * 
     * @type {number}
     * @memberof ErrorResponse
     */
    'code'?: number;
}
/**
 * 
 * @export
 * @interface GetAllUnitsPaginatedResponse
 */
export interface GetAllUnitsPaginatedResponse {
    /**
     * 
     * @type {Pagination}
     * @memberof GetAllUnitsPaginatedResponse
     */
    'pagination'?: Pagination;
    /**
     * 
     * @type {Array<UnitResponse>}
     * @memberof GetAllUnitsPaginatedResponse
     */
    'data'?: Array<UnitResponse>;
}
/**
 * 
 * @export
 * @interface Pagination
 */
export interface Pagination {
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'totalItems'?: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'pageSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'currentPage'?: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'totalPages'?: number;
}
/**
 * 
 * @export
 * @interface UnitResponse
 */
export interface UnitResponse {
    /**
     * 
     * @type {string}
     * @memberof UnitResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UnitResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UnitResponse
     */
    'abbreviation'?: string;
}

/**
 * UnitsApi - axios parameter creator
 * @export
 */
export const UnitsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new measurement unit
         * @param {CreateUnitRequest} createUnitRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUnit: async (createUnitRequest: CreateUnitRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createUnitRequest' is not null or undefined
            assertParamExists('createUnit', 'createUnitRequest', createUnitRequest)
            const localVarPath = `/api/v1/units`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createUnitRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieve a list of measurement units
         * @param {number} [from] The starting index of the units.
         * @param {number} [size] The number of units to return.
         * @param {string} [filter] Filter criteria for units.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllUnits: async (from?: number, size?: number, filter?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/units`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (from !== undefined) {
                localVarQueryParameter['from'] = from;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UnitsApi - functional programming interface
 * @export
 */
export const UnitsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UnitsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new measurement unit
         * @param {CreateUnitRequest} createUnitRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createUnit(createUnitRequest: CreateUnitRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UnitResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createUnit(createUnitRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UnitsApi.createUnit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retrieve a list of measurement units
         * @param {number} [from] The starting index of the units.
         * @param {number} [size] The number of units to return.
         * @param {string} [filter] Filter criteria for units.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllUnits(from?: number, size?: number, filter?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAllUnitsPaginatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllUnits(from, size, filter, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UnitsApi.getAllUnits']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UnitsApi - factory interface
 * @export
 */
export const UnitsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UnitsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new measurement unit
         * @param {UnitsApiCreateUnitRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUnit(requestParameters: UnitsApiCreateUnitRequest, options?: RawAxiosRequestConfig): AxiosPromise<UnitResponse> {
            return localVarFp.createUnit(requestParameters.createUnitRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieve a list of measurement units
         * @param {UnitsApiGetAllUnitsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllUnits(requestParameters: UnitsApiGetAllUnitsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<GetAllUnitsPaginatedResponse> {
            return localVarFp.getAllUnits(requestParameters.from, requestParameters.size, requestParameters.filter, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createUnit operation in UnitsApi.
 * @export
 * @interface UnitsApiCreateUnitRequest
 */
export interface UnitsApiCreateUnitRequest {
    /**
     * 
     * @type {CreateUnitRequest}
     * @memberof UnitsApiCreateUnit
     */
    readonly createUnitRequest: CreateUnitRequest
}

/**
 * Request parameters for getAllUnits operation in UnitsApi.
 * @export
 * @interface UnitsApiGetAllUnitsRequest
 */
export interface UnitsApiGetAllUnitsRequest {
    /**
     * The starting index of the units.
     * @type {number}
     * @memberof UnitsApiGetAllUnits
     */
    readonly from?: number

    /**
     * The number of units to return.
     * @type {number}
     * @memberof UnitsApiGetAllUnits
     */
    readonly size?: number

    /**
     * Filter criteria for units.
     * @type {string}
     * @memberof UnitsApiGetAllUnits
     */
    readonly filter?: string
}

/**
 * UnitsApi - object-oriented interface
 * @export
 * @class UnitsApi
 * @extends {BaseAPI}
 */
export class UnitsApi extends BaseAPI {
    /**
     * 
     * @summary Create a new measurement unit
     * @param {UnitsApiCreateUnitRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UnitsApi
     */
    public createUnit(requestParameters: UnitsApiCreateUnitRequest, options?: RawAxiosRequestConfig) {
        return UnitsApiFp(this.configuration).createUnit(requestParameters.createUnitRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieve a list of measurement units
     * @param {UnitsApiGetAllUnitsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UnitsApi
     */
    public getAllUnits(requestParameters: UnitsApiGetAllUnitsRequest = {}, options?: RawAxiosRequestConfig) {
        return UnitsApiFp(this.configuration).getAllUnits(requestParameters.from, requestParameters.size, requestParameters.filter, options).then((request) => request(this.axios, this.basePath));
    }
}



