/* tslint:disable */
/* eslint-disable */
/**
 * Fee API
 * API to manage additional fees for invoices, including discounts and taxes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface CreateFeeRequest
 */
export interface CreateFeeRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateFeeRequest
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof CreateFeeRequest
     */
    'rate': number;
    /**
     * 
     * @type {string}
     * @memberof CreateFeeRequest
     */
    'type': CreateFeeRequestTypeEnum;
}

export const CreateFeeRequestTypeEnum = {
    Discount: 'DISCOUNT',
    Tax: 'TAX'
} as const;

export type CreateFeeRequestTypeEnum = typeof CreateFeeRequestTypeEnum[keyof typeof CreateFeeRequestTypeEnum];

/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponse
     */
    'error'?: string;
    /**
     * 
     * @type {number}
     * @memberof ErrorResponse
     */
    'code'?: number;
}
/**
 * 
 * @export
 * @interface FeeResponse
 */
export interface FeeResponse {
    /**
     * 
     * @type {string}
     * @memberof FeeResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeeResponse
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof FeeResponse
     */
    'rate'?: number;
    /**
     * 
     * @type {string}
     * @memberof FeeResponse
     */
    'type'?: FeeResponseTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof FeeResponse
     */
    'createdAt'?: string;
}

export const FeeResponseTypeEnum = {
    Discount: 'DISCOUNT',
    Tax: 'TAX'
} as const;

export type FeeResponseTypeEnum = typeof FeeResponseTypeEnum[keyof typeof FeeResponseTypeEnum];

/**
 * 
 * @export
 * @interface GetAllFeesPaginatedResponse
 */
export interface GetAllFeesPaginatedResponse {
    /**
     * 
     * @type {Pagination}
     * @memberof GetAllFeesPaginatedResponse
     */
    'pagination'?: Pagination;
    /**
     * 
     * @type {Array<FeeResponse>}
     * @memberof GetAllFeesPaginatedResponse
     */
    'data'?: Array<FeeResponse>;
}
/**
 * 
 * @export
 * @interface Pagination
 */
export interface Pagination {
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'totalItems'?: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'pageSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'currentPage'?: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'totalPages'?: number;
}

/**
 * FeesApi - axios parameter creator
 * @export
 */
export const FeesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new fee
         * @param {CreateFeeRequest} createFeeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createFee: async (createFeeRequest: CreateFeeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createFeeRequest' is not null or undefined
            assertParamExists('createFee', 'createFeeRequest', createFeeRequest)
            const localVarPath = `/api/v1/fees`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createFeeRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieve a list of fees
         * @param {number} [from] The starting index of the fees.
         * @param {number} [size] The number of fees to return.
         * @param {string} [filter] Filter criteria for fees.
         * @param {GetAllFeesOrderByEnum} [orderBy] Field to order fees by.
         * @param {GetAllFeesDirectionEnum} [direction] Sorting direction.
         * @param {GetAllFeesTypeEnum} [type] Type of fee to filter by.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllFees: async (from?: number, size?: number, filter?: string, orderBy?: GetAllFeesOrderByEnum, direction?: GetAllFeesDirectionEnum, type?: GetAllFeesTypeEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/fees`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (from !== undefined) {
                localVarQueryParameter['from'] = from;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['orderBy'] = orderBy;
            }

            if (direction !== undefined) {
                localVarQueryParameter['direction'] = direction;
            }

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FeesApi - functional programming interface
 * @export
 */
export const FeesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FeesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new fee
         * @param {CreateFeeRequest} createFeeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createFee(createFeeRequest: CreateFeeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FeeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createFee(createFeeRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FeesApi.createFee']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retrieve a list of fees
         * @param {number} [from] The starting index of the fees.
         * @param {number} [size] The number of fees to return.
         * @param {string} [filter] Filter criteria for fees.
         * @param {GetAllFeesOrderByEnum} [orderBy] Field to order fees by.
         * @param {GetAllFeesDirectionEnum} [direction] Sorting direction.
         * @param {GetAllFeesTypeEnum} [type] Type of fee to filter by.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllFees(from?: number, size?: number, filter?: string, orderBy?: GetAllFeesOrderByEnum, direction?: GetAllFeesDirectionEnum, type?: GetAllFeesTypeEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAllFeesPaginatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllFees(from, size, filter, orderBy, direction, type, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FeesApi.getAllFees']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FeesApi - factory interface
 * @export
 */
export const FeesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FeesApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new fee
         * @param {FeesApiCreateFeeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createFee(requestParameters: FeesApiCreateFeeRequest, options?: RawAxiosRequestConfig): AxiosPromise<FeeResponse> {
            return localVarFp.createFee(requestParameters.createFeeRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieve a list of fees
         * @param {FeesApiGetAllFeesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllFees(requestParameters: FeesApiGetAllFeesRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<GetAllFeesPaginatedResponse> {
            return localVarFp.getAllFees(requestParameters.from, requestParameters.size, requestParameters.filter, requestParameters.orderBy, requestParameters.direction, requestParameters.type, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createFee operation in FeesApi.
 * @export
 * @interface FeesApiCreateFeeRequest
 */
export interface FeesApiCreateFeeRequest {
    /**
     * 
     * @type {CreateFeeRequest}
     * @memberof FeesApiCreateFee
     */
    readonly createFeeRequest: CreateFeeRequest
}

/**
 * Request parameters for getAllFees operation in FeesApi.
 * @export
 * @interface FeesApiGetAllFeesRequest
 */
export interface FeesApiGetAllFeesRequest {
    /**
     * The starting index of the fees.
     * @type {number}
     * @memberof FeesApiGetAllFees
     */
    readonly from?: number

    /**
     * The number of fees to return.
     * @type {number}
     * @memberof FeesApiGetAllFees
     */
    readonly size?: number

    /**
     * Filter criteria for fees.
     * @type {string}
     * @memberof FeesApiGetAllFees
     */
    readonly filter?: string

    /**
     * Field to order fees by.
     * @type {'createdAt'}
     * @memberof FeesApiGetAllFees
     */
    readonly orderBy?: GetAllFeesOrderByEnum

    /**
     * Sorting direction.
     * @type {'ASC' | 'DESC'}
     * @memberof FeesApiGetAllFees
     */
    readonly direction?: GetAllFeesDirectionEnum

    /**
     * Type of fee to filter by.
     * @type {'DISCOUNT' | 'TAX'}
     * @memberof FeesApiGetAllFees
     */
    readonly type?: GetAllFeesTypeEnum
}

/**
 * FeesApi - object-oriented interface
 * @export
 * @class FeesApi
 * @extends {BaseAPI}
 */
export class FeesApi extends BaseAPI {
    /**
     * 
     * @summary Create a new fee
     * @param {FeesApiCreateFeeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeesApi
     */
    public createFee(requestParameters: FeesApiCreateFeeRequest, options?: RawAxiosRequestConfig) {
        return FeesApiFp(this.configuration).createFee(requestParameters.createFeeRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieve a list of fees
     * @param {FeesApiGetAllFeesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeesApi
     */
    public getAllFees(requestParameters: FeesApiGetAllFeesRequest = {}, options?: RawAxiosRequestConfig) {
        return FeesApiFp(this.configuration).getAllFees(requestParameters.from, requestParameters.size, requestParameters.filter, requestParameters.orderBy, requestParameters.direction, requestParameters.type, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const GetAllFeesOrderByEnum = {
    CreatedAt: 'createdAt'
} as const;
export type GetAllFeesOrderByEnum = typeof GetAllFeesOrderByEnum[keyof typeof GetAllFeesOrderByEnum];
/**
 * @export
 */
export const GetAllFeesDirectionEnum = {
    Asc: 'ASC',
    Desc: 'DESC'
} as const;
export type GetAllFeesDirectionEnum = typeof GetAllFeesDirectionEnum[keyof typeof GetAllFeesDirectionEnum];
/**
 * @export
 */
export const GetAllFeesTypeEnum = {
    Discount: 'DISCOUNT',
    Tax: 'TAX'
} as const;
export type GetAllFeesTypeEnum = typeof GetAllFeesTypeEnum[keyof typeof GetAllFeesTypeEnum];


