/* tslint:disable */
/* eslint-disable */
/**
 * Fee API
 * API to manage additional fees for invoices, including discounts and taxes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

