/* tslint:disable */
/* eslint-disable */
/**
 * User API
 * API for managing authentication and user login/registration between Next.js and Spring Boot.
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface AuthProvider
 */
export interface AuthProvider {
    /**
     * The authentication provider for the user.
     * @type {string}
     * @memberof AuthProvider
     */
    'authProvider': AuthProviderAuthProviderEnum;
    /**
     * The ID token from the authentication provider (e.g., Google or Microsoft).
     * @type {string}
     * @memberof AuthProvider
     */
    'authProviderIdToken'?: string;
}

export const AuthProviderAuthProviderEnum = {
    Google: 'google',
    Microsoft: 'microsoft',
    Facebook: 'facebook',
    Email: 'email'
} as const;

export type AuthProviderAuthProviderEnum = typeof AuthProviderAuthProviderEnum[keyof typeof AuthProviderAuthProviderEnum];

/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * The status of the call (e.g., error).
     * @type {string}
     * @memberof ErrorResponse
     */
    'status'?: string;
    /**
     * A description of the error.
     * @type {string}
     * @memberof ErrorResponse
     */
    'message'?: string;
    /**
     * The HTTP error code (e.g., 400, 500).
     * @type {number}
     * @memberof ErrorResponse
     */
    'code'?: number;
    /**
     * Additional error details, if any.
     * @type {string}
     * @memberof ErrorResponse
     */
    'details'?: string;
}
/**
 * 
 * @export
 * @interface LoginRequest
 */
export interface LoginRequest {
    /**
     * 
     * @type {AuthProvider}
     * @memberof LoginRequest
     */
    'provider': AuthProvider;
    /**
     * 
     * @type {UserCredentials}
     * @memberof LoginRequest
     */
    'credentials': UserCredentials;
}
/**
 * 
 * @export
 * @interface OtpResendResponse
 */
export interface OtpResendResponse {
    /**
     * A list of messages related to the OTP resend operation.
     * @type {Array<string>}
     * @memberof OtpResendResponse
     */
    'messages'?: Array<string>;
}
/**
 * 
 * @export
 * @interface OtpSendResponse
 */
export interface OtpSendResponse {
    /**
     * A list of messages related to the OTP resend operation.
     * @type {Array<string>}
     * @memberof OtpSendResponse
     */
    'messages'?: Array<string>;
}
/**
 * 
 * @export
 * @interface OtpVerifyResponse
 */
export interface OtpVerifyResponse {
    /**
     * A list of messages related to the OTP verification operation.
     * @type {Array<string>}
     * @memberof OtpVerifyResponse
     */
    'messages'?: Array<string>;
}
/**
 * 
 * @export
 * @interface RegisterRequest
 */
export interface RegisterRequest {
    /**
     * 
     * @type {AuthProvider}
     * @memberof RegisterRequest
     */
    'provider': AuthProvider;
    /**
     * 
     * @type {UserRegistrationDetails}
     * @memberof RegisterRequest
     */
    'user': UserRegistrationDetails;
}
/**
 * 
 * @export
 * @interface ResendOtpRequest
 */
export interface ResendOtpRequest {
    /**
     * The user\'s email address to which the OTP will be resent.
     * @type {string}
     * @memberof ResendOtpRequest
     */
    'email': string;
}
/**
 * 
 * @export
 * @interface SendEmailOtpRequest
 */
export interface SendEmailOtpRequest {
    /**
     * The user\'s email to which the OTP will be sent.
     * @type {string}
     * @memberof SendEmailOtpRequest
     */
    'email': string;
}
/**
 * 
 * @export
 * @interface Tokens
 */
export interface Tokens {
    /**
     * The JWT access token for authenticating subsequent requests.
     * @type {string}
     * @memberof Tokens
     */
    'accessToken'?: string;
    /**
     * The expiration date and time of the access token in ISO 8601 format.
     * @type {string}
     * @memberof Tokens
     */
    'accessTokenExpiresAt'?: string;
    /**
     * The refresh token for obtaining new access tokens.
     * @type {string}
     * @memberof Tokens
     */
    'refreshToken'?: string;
    /**
     * The expiration date and time of the refresh token in ISO 8601 format.
     * @type {string}
     * @memberof Tokens
     */
    'refreshTokenExpiresAt'?: string;
}
/**
 * 
 * @export
 * @interface UserAuthenticationResponse
 */
export interface UserAuthenticationResponse {
    /**
     * The status of the call (e.g., success, error).
     * @type {string}
     * @memberof UserAuthenticationResponse
     */
    'status'?: string;
    /**
     * A list of messages related to the status of the request.
     * @type {Array<string>}
     * @memberof UserAuthenticationResponse
     */
    'messages'?: Array<string>;
    /**
     * 
     * @type {UserAuthenticationResponseData}
     * @memberof UserAuthenticationResponse
     */
    'data'?: UserAuthenticationResponseData;
}
/**
 * Contains relevant data. This could be user data for registration or tokens for login.
 * @export
 * @interface UserAuthenticationResponseData
 */
export interface UserAuthenticationResponseData {
    data(data: any): unknown;
    access_token: any;
    /**
     * 
     * @type {UserResponse}
     * @memberof UserAuthenticationResponseData
     */
    'user'?: UserResponse;
    /**
     * 
     * @type {Tokens}
     * @memberof UserAuthenticationResponseData
     */
    'tokens'?: Tokens;
}
/**
 * 
 * @export
 * @interface UserCredentials
 */
export interface UserCredentials {
    /**
     * The user\'s email address.
     * @type {string}
     * @memberof UserCredentials
     */
    'email': string;
    /**
     * The user\'s password.
     * @type {string}
     * @memberof UserCredentials
     */
    'password'?: string;
}
/**
 * 
 * @export
 * @interface UserLogoUploadResponse
 */
export interface UserLogoUploadResponse {
    /**
     * The status of the call (e.g., success, error).
     * @type {string}
     * @memberof UserLogoUploadResponse
     */
    'status'?: string;
    /**
     * A list of messages related to the status of the request.
     * @type {Array<string>}
     * @memberof UserLogoUploadResponse
     */
    'messages'?: Array<string>;
    /**
     * 
     * @type {UserLogoUploadResponseData}
     * @memberof UserLogoUploadResponse
     */
    'data'?: UserLogoUploadResponseData;
}
/**
 * Contains relevant data. This could be user data for registration or tokens for login.
 * @export
 * @interface UserLogoUploadResponseData
 */
export interface UserLogoUploadResponseData {
    /**
     * The URL to access the uploaded logo.
     * @type {string}
     * @memberof UserLogoUploadResponseData
     */
    'url'?: string;
}
/**
 * 
 * @export
 * @interface UserRegistrationDetails
 */
export interface UserRegistrationDetails {
    /**
     * User business name
     * @type {string}
     * @memberof UserRegistrationDetails
     */
    'businessName': string;
    /**
     * User address.
     * @type {string}
     * @memberof UserRegistrationDetails
     */
    'address': string;
    /**
     * Taxpayer Identification Number (TIN) for companies in the USA, formatted as XX-XXXXXXX.
     * @type {string}
     * @memberof UserRegistrationDetails
     */
    'taxNumber'?: string;
    /**
     * The user\'s phone number in international format.
     * @type {string}
     * @memberof UserRegistrationDetails
     */
    'phoneNumber'?: string;
    /**
     * A country where business is hosted.
     * @type {string}
     * @memberof UserRegistrationDetails
     */
    'country': string;
    /**
     * A country state where business is hosted.
     * @type {string}
     * @memberof UserRegistrationDetails
     */
    'state'?: string;
    /**
     * A city where business is hosted.
     * @type {string}
     * @memberof UserRegistrationDetails
     */
    'city': string;
    /**
     * The postal code or ZIP code of the user\'s business location.
     * @type {string}
     * @memberof UserRegistrationDetails
     */
    'zipCode': string;
    /**
     * URL to the user\'s website.
     * @type {string}
     * @memberof UserRegistrationDetails
     */
    'webSite'?: string;
    /**
     * 
     * @type {UserCredentials}
     * @memberof UserRegistrationDetails
     */
    'credentials': UserCredentials;
}
/**
 * 
 * @export
 * @interface UserResponse
 */
export interface UserResponse {
    /**
     * The unique ID of the registered user.
     * @type {string}
     * @memberof UserResponse
     */
    'id'?: string;
    /**
     * business data
     * @type {string}
     * @memberof UserResponse
     */
    'businessName'?: string;
    /**
     * business address
     * @type {string}
     * @memberof UserResponse
     */
    'businessAddress'?: string;
    /**
     * The user\'s email address.
     * @type {string}
     * @memberof UserResponse
     */
    'email'?: string;
    /**
     * URL to the user\'s profile picture.
     * @type {string}
     * @memberof UserResponse
     */
    'picture'?: string;
    /**
     * User Tax number
     * @type {string}
     * @memberof UserResponse
     */
    'taxNumber'?: string;
    /**
     * The user\'s phone number in international format.
     * @type {string}
     * @memberof UserResponse
     */
    'phoneNumber'?: string;
    /**
     * A country where business is hosted.
     * @type {string}
     * @memberof UserResponse
     */
    'country'?: string;
    /**
     * A city where business is hosted.
     * @type {string}
     * @memberof UserResponse
     */
    'city'?: string;
    /**
     * The postal code or ZIP code of the user\'s business location.
     * @type {string}
     * @memberof UserResponse
     */
    'zipCode'?: string;
    /**
     * URL to the user\'s website.
     * @type {string}
     * @memberof UserResponse
     */
    'webSite'?: string;
    /**
     * A country state where business is hosted.
     * @type {string}
     * @memberof UserResponse
     */
    'state'?: string;
}
/**
 * 
 * @export
 * @interface UserResponseEnriched
 */
export interface UserResponseEnriched {
    /**
     * 
     * @type {UserResponse}
     * @memberof UserResponseEnriched
     */
    'user'?: UserResponse;
    /**
     * 
     * @type {UserResponseEnrichedPlan}
     * @memberof UserResponseEnriched
     */
    'plan'?: UserResponseEnrichedPlan;
}
/**
 * 
 * @export
 * @interface UserResponseEnrichedPlan
 */
export interface UserResponseEnrichedPlan {
    /**
     * Name of the current plan (e.g., trial, free, pro)
     * @type {string}
     * @memberof UserResponseEnrichedPlan
     */
    'name'?: string;
    /**
     * List of permissions granted by this plan
     * @type {Array<string>}
     * @memberof UserResponseEnrichedPlan
     */
    'permissions'?: Array<string>;
}
/**
 * 
 * @export
 * @interface UserUpdateDetails
 */
export interface UserUpdateDetails {
    /**
     * 
     * @type {string}
     * @memberof UserUpdateDetails
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateDetails
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateDetails
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateDetails
     */
    'companyName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateDetails
     */
    'companyAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateDetails
     */
    'companyTaxNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateDetails
     */
    'zipCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateDetails
     */
    'site'?: string;
}
/**
 * 
 * @export
 * @interface VerifyEmailOtpRequest
 */
export interface VerifyEmailOtpRequest {
    /**
     * The user\'s email address.
     * @type {string}
     * @memberof VerifyEmailOtpRequest
     */
    'email': string;
    /**
     * The OTP code sent to the user\'s email.
     * @type {string}
     * @memberof VerifyEmailOtpRequest
     */
    'otp': string;
}

/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns information about the authenticated user, including their roles and permissions.
         * @summary Get current user information
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentUser: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/users/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Logs in a user using credentials for a specific provider. Returns access and refresh tokens.
         * @summary Login with credentials from an authentication provider
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (loginRequest: LoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginRequest' is not null or undefined
            assertParamExists('login', 'loginRequest', loginRequest)
            const localVarPath = `/user/user_auth/login/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Registers a user with data provided from an authentication provider. If the user doesn\'t exist, creates a new account.
         * @summary Register a new user
         * @param {RegisterRequest} registerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUser: async (registerRequest: RegisterRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'registerRequest' is not null or undefined
            assertParamExists('registerUser', 'registerRequest', registerRequest)
            const localVarPath = `/user/user_auth/signup/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Resends a new OTP to the user\'s email address for verification.
         * @summary Resend OTP to user\'s email
         * @param {ResendOtpRequest} resendOtpRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resendEmailOtp: async (resendOtpRequest: ResendOtpRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'resendOtpRequest' is not null or undefined
            assertParamExists('resendEmailOtp', 'resendOtpRequest', resendOtpRequest)
            const localVarPath = `/user/verify/re_send_otp/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(resendOtpRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Sends a one-time password (OTP) to the user\'s email address for verification purposes.
         * @summary Send OTP to email
         * @param {SendEmailOtpRequest} sendEmailOtpRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendEmailOtp: async (sendEmailOtpRequest: SendEmailOtpRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sendEmailOtpRequest' is not null or undefined
            assertParamExists('sendEmailOtp', 'sendEmailOtpRequest', sendEmailOtpRequest)
            const localVarPath = `/user/verify/send_otp/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sendEmailOtpRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Allows the authenticated user to update their profile information, excluding the email.
         * @summary Update current user information
         * @param {UserUpdateDetails} userUpdateDetails 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCurrentUser: async (userUpdateDetails: UserUpdateDetails, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userUpdateDetails' is not null or undefined
            assertParamExists('updateCurrentUser', 'userUpdateDetails', userUpdateDetails)
            const localVarPath = `/api/v1/users/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userUpdateDetails, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Accepts an image file and responds with a URL to access the uploaded logo.
         * @summary Upload a user logo
         * @param {File} [file] The image file to be uploaded.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadUserLogo: async (file?: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/users/logo/upload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Verifies the one-time password (OTP) submitted by the user for email confirmation.
         * @summary Verify OTP for email
         * @param {VerifyEmailOtpRequest} verifyEmailOtpRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyEmailOtp: async (verifyEmailOtpRequest: VerifyEmailOtpRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'verifyEmailOtpRequest' is not null or undefined
            assertParamExists('verifyEmailOtp', 'verifyEmailOtpRequest', verifyEmailOtpRequest)
            const localVarPath = `/user/verify/verify_otp/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(verifyEmailOtpRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns information about the authenticated user, including their roles and permissions.
         * @summary Get current user information
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCurrentUser(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponseEnriched>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCurrentUser(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getCurrentUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Logs in a user using credentials for a specific provider. Returns access and refresh tokens.
         * @summary Login with credentials from an authentication provider
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserAuthenticationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(loginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.login']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Registers a user with data provided from an authentication provider. If the user doesn\'t exist, creates a new account.
         * @summary Register a new user
         * @param {RegisterRequest} registerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerUser(registerRequest: RegisterRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserAuthenticationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerUser(registerRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.registerUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Resends a new OTP to the user\'s email address for verification.
         * @summary Resend OTP to user\'s email
         * @param {ResendOtpRequest} resendOtpRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resendEmailOtp(resendOtpRequest: ResendOtpRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OtpResendResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.resendEmailOtp(resendOtpRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.resendEmailOtp']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Sends a one-time password (OTP) to the user\'s email address for verification purposes.
         * @summary Send OTP to email
         * @param {SendEmailOtpRequest} sendEmailOtpRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendEmailOtp(sendEmailOtpRequest: SendEmailOtpRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OtpSendResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendEmailOtp(sendEmailOtpRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.sendEmailOtp']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Allows the authenticated user to update their profile information, excluding the email.
         * @summary Update current user information
         * @param {UserUpdateDetails} userUpdateDetails 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCurrentUser(userUpdateDetails: UserUpdateDetails, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCurrentUser(userUpdateDetails, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.updateCurrentUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Accepts an image file and responds with a URL to access the uploaded logo.
         * @summary Upload a user logo
         * @param {File} [file] The image file to be uploaded.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadUserLogo(file?: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserLogoUploadResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadUserLogo(file, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.uploadUserLogo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Verifies the one-time password (OTP) submitted by the user for email confirmation.
         * @summary Verify OTP for email
         * @param {VerifyEmailOtpRequest} verifyEmailOtpRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async verifyEmailOtp(verifyEmailOtpRequest: VerifyEmailOtpRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OtpVerifyResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.verifyEmailOtp(verifyEmailOtpRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.verifyEmailOtp']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * Returns information about the authenticated user, including their roles and permissions.
         * @summary Get current user information
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentUser(options?: RawAxiosRequestConfig): AxiosPromise<UserResponseEnriched> {
            return localVarFp.getCurrentUser(options).then((request) => request(axios, basePath));
        },
        /**
         * Logs in a user using credentials for a specific provider. Returns access and refresh tokens.
         * @summary Login with credentials from an authentication provider
         * @param {UserApiLoginRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(requestParameters: UserApiLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserAuthenticationResponse> {
            return localVarFp.login(requestParameters.loginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Registers a user with data provided from an authentication provider. If the user doesn\'t exist, creates a new account.
         * @summary Register a new user
         * @param {UserApiRegisterUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUser(requestParameters: UserApiRegisterUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserAuthenticationResponse> {
            return localVarFp.registerUser(requestParameters.registerRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Resends a new OTP to the user\'s email address for verification.
         * @summary Resend OTP to user\'s email
         * @param {UserApiResendEmailOtpRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resendEmailOtp(requestParameters: UserApiResendEmailOtpRequest, options?: RawAxiosRequestConfig): AxiosPromise<OtpResendResponse> {
            return localVarFp.resendEmailOtp(requestParameters.resendOtpRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Sends a one-time password (OTP) to the user\'s email address for verification purposes.
         * @summary Send OTP to email
         * @param {UserApiSendEmailOtpRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendEmailOtp(requestParameters: UserApiSendEmailOtpRequest, options?: RawAxiosRequestConfig): AxiosPromise<OtpSendResponse> {
            return localVarFp.sendEmailOtp(requestParameters.sendEmailOtpRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Allows the authenticated user to update their profile information, excluding the email.
         * @summary Update current user information
         * @param {UserApiUpdateCurrentUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCurrentUser(requestParameters: UserApiUpdateCurrentUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserResponse> {
            return localVarFp.updateCurrentUser(requestParameters.userUpdateDetails, options).then((request) => request(axios, basePath));
        },
        /**
         * Accepts an image file and responds with a URL to access the uploaded logo.
         * @summary Upload a user logo
         * @param {UserApiUploadUserLogoRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadUserLogo(requestParameters: UserApiUploadUserLogoRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<UserLogoUploadResponse> {
            return localVarFp.uploadUserLogo(requestParameters.file, options).then((request) => request(axios, basePath));
        },
        /**
         * Verifies the one-time password (OTP) submitted by the user for email confirmation.
         * @summary Verify OTP for email
         * @param {UserApiVerifyEmailOtpRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyEmailOtp(requestParameters: UserApiVerifyEmailOtpRequest, options?: RawAxiosRequestConfig): AxiosPromise<OtpVerifyResponse> {
            return localVarFp.verifyEmailOtp(requestParameters.verifyEmailOtpRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for login operation in UserApi.
 * @export
 * @interface UserApiLoginRequest
 */
export interface UserApiLoginRequest {
    /**
     * 
     * @type {LoginRequest}
     * @memberof UserApiLogin
     */
    readonly loginRequest: LoginRequest
}

/**
 * Request parameters for registerUser operation in UserApi.
 * @export
 * @interface UserApiRegisterUserRequest
 */
export interface UserApiRegisterUserRequest {
    /**
     * 
     * @type {RegisterRequest}
     * @memberof UserApiRegisterUser
     */
    readonly registerRequest: RegisterRequest
}

/**
 * Request parameters for resendEmailOtp operation in UserApi.
 * @export
 * @interface UserApiResendEmailOtpRequest
 */
export interface UserApiResendEmailOtpRequest {
    /**
     * 
     * @type {ResendOtpRequest}
     * @memberof UserApiResendEmailOtp
     */
    readonly resendOtpRequest: ResendOtpRequest
}

/**
 * Request parameters for sendEmailOtp operation in UserApi.
 * @export
 * @interface UserApiSendEmailOtpRequest
 */
export interface UserApiSendEmailOtpRequest {
    /**
     * 
     * @type {SendEmailOtpRequest}
     * @memberof UserApiSendEmailOtp
     */
    readonly sendEmailOtpRequest: SendEmailOtpRequest
}

/**
 * Request parameters for updateCurrentUser operation in UserApi.
 * @export
 * @interface UserApiUpdateCurrentUserRequest
 */
export interface UserApiUpdateCurrentUserRequest {
    /**
     * 
     * @type {UserUpdateDetails}
     * @memberof UserApiUpdateCurrentUser
     */
    readonly userUpdateDetails: UserUpdateDetails
}

/**
 * Request parameters for uploadUserLogo operation in UserApi.
 * @export
 * @interface UserApiUploadUserLogoRequest
 */
export interface UserApiUploadUserLogoRequest {
    /**
     * The image file to be uploaded.
     * @type {File}
     * @memberof UserApiUploadUserLogo
     */
    readonly file?: File
}

/**
 * Request parameters for verifyEmailOtp operation in UserApi.
 * @export
 * @interface UserApiVerifyEmailOtpRequest
 */
export interface UserApiVerifyEmailOtpRequest {
    /**
     * 
     * @type {VerifyEmailOtpRequest}
     * @memberof UserApiVerifyEmailOtp
     */
    readonly verifyEmailOtpRequest: VerifyEmailOtpRequest
}

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI {
    /**
     * Returns information about the authenticated user, including their roles and permissions.
     * @summary Get current user information
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public getCurrentUser(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getCurrentUser(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Logs in a user using credentials for a specific provider. Returns access and refresh tokens.
     * @summary Login with credentials from an authentication provider
     * @param {UserApiLoginRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public login(requestParameters: UserApiLoginRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).login(requestParameters.loginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Registers a user with data provided from an authentication provider. If the user doesn\'t exist, creates a new account.
     * @summary Register a new user
     * @param {UserApiRegisterUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public registerUser(requestParameters: UserApiRegisterUserRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).registerUser(requestParameters.registerRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Resends a new OTP to the user\'s email address for verification.
     * @summary Resend OTP to user\'s email
     * @param {UserApiResendEmailOtpRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public resendEmailOtp(requestParameters: UserApiResendEmailOtpRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).resendEmailOtp(requestParameters.resendOtpRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Sends a one-time password (OTP) to the user\'s email address for verification purposes.
     * @summary Send OTP to email
     * @param {UserApiSendEmailOtpRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public sendEmailOtp(requestParameters: UserApiSendEmailOtpRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).sendEmailOtp(requestParameters.sendEmailOtpRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Allows the authenticated user to update their profile information, excluding the email.
     * @summary Update current user information
     * @param {UserApiUpdateCurrentUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public updateCurrentUser(requestParameters: UserApiUpdateCurrentUserRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).updateCurrentUser(requestParameters.userUpdateDetails, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Accepts an image file and responds with a URL to access the uploaded logo.
     * @summary Upload a user logo
     * @param {UserApiUploadUserLogoRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public uploadUserLogo(requestParameters: UserApiUploadUserLogoRequest = {}, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).uploadUserLogo(requestParameters.file, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Verifies the one-time password (OTP) submitted by the user for email confirmation.
     * @summary Verify OTP for email
     * @param {UserApiVerifyEmailOtpRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public verifyEmailOtp(requestParameters: UserApiVerifyEmailOtpRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).verifyEmailOtp(requestParameters.verifyEmailOtpRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



