/* tslint:disable */
/* eslint-disable */
/**
 * Client API
 * API to retrieve and create client information
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 *
 * @export
 * @interface ClientResponse
 */
export interface ClientResponse {
  /**
   *
   * @type {string}
   * @memberof ClientResponse
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof ClientResponse
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof ClientResponse
   */
  address?: string;
  /**
   *
   * @type {string}
   * @memberof ClientResponse
   */
  phone?: string;
  /**
   *
   * @type {string}
   * @memberof ClientResponse
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof ClientResponse
   */
  website?: string;
  /**
   *
   * @type {string}
   * @memberof ClientResponse
   */
  observation?: string;
}
/**
 *
 * @export
 * @interface CreateClientRequest
 */
export interface CreateClientRequest {
  /**
   *
   * @type {string}
   * @memberof CreateClientRequest
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof CreateClientRequest
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof CreateClientRequest
   */
  phone?: string;
  /**
   *
   * @type {string}
   * @memberof CreateClientRequest
   */
  address?: string;
  /**
   *
   * @type {string}
   * @memberof CreateClientRequest
   */
  website?: string;
  /**
   *
   * @type {string}
   * @memberof CreateClientRequest
   */
  observation?: string;
}
/**
 *
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
  /**
   *
   * @type {string}
   * @memberof ErrorResponse
   */
  error?: string;
  /**
   *
   * @type {number}
   * @memberof ErrorResponse
   */
  code?: number;
}
/**
 *
 * @export
 * @interface GetAllClientsPaginatedResponse
 */
export interface GetAllClientsPaginatedResponse {
  /**
   *
   * @type {Pagination}
   * @memberof GetAllClientsPaginatedResponse
   */
  pagination?: Pagination;
  /**
   *
   * @type {Array<ClientResponse>}
   * @memberof GetAllClientsPaginatedResponse
   */
  data?: Array<ClientResponse>;
}
/**
 *
 * @export
 * @interface Pagination
 */
export interface Pagination {
  /**
   *
   * @type {number}
   * @memberof Pagination
   */
  totalItems?: number;
  /**
   *
   * @type {number}
   * @memberof Pagination
   */
  pageSize?: number;
  /**
   *
   * @type {number}
   * @memberof Pagination
   */
  currentPage?: number;
  /**
   *
   * @type {number}
   * @memberof Pagination
   */
  totalPages?: number;
}
/**
 *
 * @export
 * @interface UpdateClientRequest
 */
export interface UpdateClientRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateClientRequest
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateClientRequest
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateClientRequest
   */
  phone?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateClientRequest
   */
  address?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateClientRequest
   */
  website?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateClientRequest
   */
  observation?: string;
}

/**
 * ClientsApi - axios parameter creator
 * @export
 */
export const ClientsApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Create a new client
     * @param {CreateClientRequest} createClientRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createClient: async (
      createClientRequest: CreateClientRequest,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'createClientRequest' is not null or undefined
      assertParamExists('createClient', 'createClientRequest', createClientRequest);
      const localVarPath = `/user/client/create_client/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
      localVarRequestOptions.data = serializeDataIfNeeded(createClientRequest, localVarRequestOptions, configuration);

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Delete a client by ID
     * @param {string} id Unique identifier of the client to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteClient: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('deleteClient', 'id', id);
      const localVarPath = `/api/v1/clients/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(id)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Retrieve a list of clients
     * @param {number} [from] The starting index of the invoices.
     * @param {number} [size] The number of invoices to return.
     * @param {string} [filter] Filter criteria for invoices.
     * @param {GetClientsOrderByEnum} [orderBy] Field to order clients by.
     * @param {GetClientsDirectionEnum} [direction] Sorting direction.
     * @param {GetClientsStatusEnum} [status] Filter clients by their status.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getClients: async (
      from?: number,
      size?: number,
      filter?: string,
      orderBy?: GetClientsOrderByEnum,
      direction?: GetClientsDirectionEnum,
      status?: GetClientsStatusEnum,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/user/client/list_clients/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (from !== undefined) {
        localVarQueryParameter['from'] = from;
      }

      if (size !== undefined) {
        localVarQueryParameter['size'] = size;
      }

      if (filter !== undefined) {
        localVarQueryParameter['filter'] = filter;
      }

      if (orderBy !== undefined) {
        localVarQueryParameter['orderBy'] = orderBy;
      }

      if (direction !== undefined) {
        localVarQueryParameter['direction'] = direction;
      }

      if (status !== undefined) {
        localVarQueryParameter['status'] = status;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Update an existing client
     * @param {string} id Unique identifier of the client to update
     * @param {UpdateClientRequest} updateClientRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateClient: async (
      id: string,
      updateClientRequest: UpdateClientRequest,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('updateClient', 'id', id);
      // verify required parameter 'updateClientRequest' is not null or undefined
      assertParamExists('updateClient', 'updateClientRequest', updateClientRequest);
      const localVarPath = `/user/client/update_client/?client_id=${id}`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
      localVarRequestOptions.data = serializeDataIfNeeded(updateClientRequest, localVarRequestOptions, configuration);

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * ClientsApi - functional programming interface
 * @export
 */
export const ClientsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = ClientsApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Create a new client
     * @param {CreateClientRequest} createClientRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createClient(
      createClientRequest: CreateClientRequest,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ClientResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createClient(createClientRequest, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ClientsApi.createClient']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Delete a client by ID
     * @param {string} id Unique identifier of the client to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteClient(
      id: string,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteClient(id, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ClientsApi.deleteClient']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Retrieve a list of clients
     * @param {number} [from] The starting index of the invoices.
     * @param {number} [size] The number of invoices to return.
     * @param {string} [filter] Filter criteria for invoices.
     * @param {GetClientsOrderByEnum} [orderBy] Field to order clients by.
     * @param {GetClientsDirectionEnum} [direction] Sorting direction.
     * @param {GetClientsStatusEnum} [status] Filter clients by their status.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getClients(
      from?: number,
      size?: number,
      filter?: string,
      orderBy?: GetClientsOrderByEnum,
      direction?: GetClientsDirectionEnum,
      status?: GetClientsStatusEnum,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAllClientsPaginatedResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getClients(
        from,
        size,
        filter,
        orderBy,
        direction,
        status,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ClientsApi.getClients']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Update an existing client
     * @param {string} id Unique identifier of the client to update
     * @param {UpdateClientRequest} updateClientRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateClient(
      id: string,
      updateClientRequest: UpdateClientRequest,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ClientResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateClient(id, updateClientRequest, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ClientsApi.updateClient']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * ClientsApi - factory interface
 * @export
 */
export const ClientsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = ClientsApiFp(configuration);
  return {
    /**
     *
     * @summary Create a new client
     * @param {ClientsApiCreateClientRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createClient(
      requestParameters: ClientsApiCreateClientRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ClientResponse> {
      return localVarFp
        .createClient(requestParameters.createClientRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Delete a client by ID
     * @param {ClientsApiDeleteClientRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteClient(
      requestParameters: ClientsApiDeleteClientRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<void> {
      return localVarFp.deleteClient(requestParameters.id, options).then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Retrieve a list of clients
     * @param {ClientsApiGetClientsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getClients(
      requestParameters: ClientsApiGetClientsRequest = {},
      options?: RawAxiosRequestConfig
    ): AxiosPromise<GetAllClientsPaginatedResponse> {
      return localVarFp
        .getClients(
          requestParameters.from,
          requestParameters.size,
          requestParameters.filter,
          requestParameters.orderBy,
          requestParameters.direction,
          requestParameters.status,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Update an existing client
     * @param {ClientsApiUpdateClientRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateClient(
      requestParameters: ClientsApiUpdateClientRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ClientResponse> {
      return localVarFp
        .updateClient(requestParameters.id, requestParameters.updateClientRequest, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for createClient operation in ClientsApi.
 * @export
 * @interface ClientsApiCreateClientRequest
 */
export interface ClientsApiCreateClientRequest {
  /**
   *
   * @type {CreateClientRequest}
   * @memberof ClientsApiCreateClient
   */
  readonly createClientRequest: CreateClientRequest;
}

/**
 * Request parameters for deleteClient operation in ClientsApi.
 * @export
 * @interface ClientsApiDeleteClientRequest
 */
export interface ClientsApiDeleteClientRequest {
  /**
   * Unique identifier of the client to delete
   * @type {string}
   * @memberof ClientsApiDeleteClient
   */
  readonly id: string;
}

/**
 * Request parameters for getClients operation in ClientsApi.
 * @export
 * @interface ClientsApiGetClientsRequest
 */
export interface ClientsApiGetClientsRequest {
  /**
   * The starting index of the invoices.
   * @type {number}
   * @memberof ClientsApiGetClients
   */
  readonly from?: number;

  /**
   * The number of invoices to return.
   * @type {number}
   * @memberof ClientsApiGetClients
   */
  readonly size?: number;

  /**
   * Filter criteria for invoices.
   * @type {string}
   * @memberof ClientsApiGetClients
   */
  readonly filter?: string;

  /**
   * Field to order clients by.
   * @type {'createdAt'}
   * @memberof ClientsApiGetClients
   */
  readonly orderBy?: GetClientsOrderByEnum;

  /**
   * Sorting direction.
   * @type {'ASC' | 'DESC'}
   * @memberof ClientsApiGetClients
   */
  readonly direction?: GetClientsDirectionEnum;

  /**
   * Filter clients by their status.
   * @type {'ACTIVE' | 'INACTIVE'}
   * @memberof ClientsApiGetClients
   */
  readonly status?: GetClientsStatusEnum;
}

/**
 * Request parameters for updateClient operation in ClientsApi.
 * @export
 * @interface ClientsApiUpdateClientRequest
 */
export interface ClientsApiUpdateClientRequest {
  /**
   * Unique identifier of the client to update
   * @type {string}
   * @memberof ClientsApiUpdateClient
   */
  readonly id: string;

  /**
   *
   * @type {UpdateClientRequest}
   * @memberof ClientsApiUpdateClient
   */
  readonly updateClientRequest: UpdateClientRequest;
}

/**
 * ClientsApi - object-oriented interface
 * @export
 * @class ClientsApi
 * @extends {BaseAPI}
 */
export class ClientsApi extends BaseAPI {
  /**
   *
   * @summary Create a new client
   * @param {ClientsApiCreateClientRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ClientsApi
   */
  public createClient(requestParameters: ClientsApiCreateClientRequest, options?: RawAxiosRequestConfig) {
    return ClientsApiFp(this.configuration)
      .createClient(requestParameters.createClientRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Delete a client by ID
   * @param {ClientsApiDeleteClientRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ClientsApi
   */
  public deleteClient(requestParameters: ClientsApiDeleteClientRequest, options?: RawAxiosRequestConfig) {
    return ClientsApiFp(this.configuration)
      .deleteClient(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Retrieve a list of clients
   * @param {ClientsApiGetClientsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ClientsApi
   */
  public getClients(requestParameters: ClientsApiGetClientsRequest = {}, options?: RawAxiosRequestConfig) {
    return ClientsApiFp(this.configuration)
      .getClients(
        requestParameters.from,
        requestParameters.size,
        requestParameters.filter,
        requestParameters.orderBy,
        requestParameters.direction,
        requestParameters.status,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Update an existing client
   * @param {ClientsApiUpdateClientRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ClientsApi
   */
  public updateClient(requestParameters: ClientsApiUpdateClientRequest, options?: RawAxiosRequestConfig) {
    return ClientsApiFp(this.configuration)
      .updateClient(requestParameters.id, requestParameters.updateClientRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }
}

/**
 * @export
 */
export const GetClientsOrderByEnum = {
  CreatedAt: 'createdAt',
} as const;
export type GetClientsOrderByEnum = (typeof GetClientsOrderByEnum)[keyof typeof GetClientsOrderByEnum];
/**
 * @export
 */
export const GetClientsDirectionEnum = {
  Asc: 'ASC',
  Desc: 'DESC',
} as const;
export type GetClientsDirectionEnum = (typeof GetClientsDirectionEnum)[keyof typeof GetClientsDirectionEnum];
/**
 * @export
 */
export const GetClientsStatusEnum = {
  Active: 'ACTIVE',
  Inactive: 'INACTIVE',
} as const;
export type GetClientsStatusEnum = (typeof GetClientsStatusEnum)[keyof typeof GetClientsStatusEnum];
