/* tslint:disable */
/* eslint-disable */
/**
 * Subscription API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
//   setApiKeyToObject,
//   setBasicAuthToObject,
//   setBearerAuthToObject,
//   setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 *
 * @export
 * @interface BillingOptionDto
 */
export interface BillingOptionDto {
  /**
   *
   * @type {string}
   * @memberof BillingOptionDto
   */
  interval?: BillingOptionDtoIntervalEnum;
  /**
   *
   * @type {number}
   * @memberof BillingOptionDto
   */
  price?: number;
  /**
   *
   * @type {string}
   * @memberof BillingOptionDto
   */
  currency?: string;
  /**
   *
   * @type {string}
   * @memberof BillingOptionDto
   */
  priceId?: string;
}

export const BillingOptionDtoIntervalEnum = {
  Monthly: 'monthly',
  Annually: 'annually',
} as const;

export type BillingOptionDtoIntervalEnum =
  (typeof BillingOptionDtoIntervalEnum)[keyof typeof BillingOptionDtoIntervalEnum];

/**
 *
 * @export
 * @interface CancelSubscriptionResponse
 */
export interface CancelSubscriptionResponse {
  /**
   *
   * @type {string}
   * @memberof CancelSubscriptionResponse
   */
  subscriptionId?: string;
  /**
   *
   * @type {string}
   * @memberof CancelSubscriptionResponse
   */
  canceledAt?: string;
  /**
   *
   * @type {string}
   * @memberof CancelSubscriptionResponse
   */
  status?: CancelSubscriptionResponseStatusEnum;
}

export const CancelSubscriptionResponseStatusEnum = {
  Canceled: 'canceled',
  Error: 'error',
} as const;

export type CancelSubscriptionResponseStatusEnum =
  (typeof CancelSubscriptionResponseStatusEnum)[keyof typeof CancelSubscriptionResponseStatusEnum];

/**
 *
 * @export
 * @interface CheckPaymentStatusRequest
 */
export interface CheckPaymentStatusRequest {
  /**
   *
   * @type {string}
   * @memberof CheckPaymentStatusRequest
   */
  sessionId: string;
}
/**
 *
 * @export
 * @interface CheckPaymentStatusResponse
 */
export interface CheckPaymentStatusResponse {
  /**
   *
   * @type {string}
   * @memberof CheckPaymentStatusResponse
   */
  sessionId?: string;
  /**
   *
   * @type {string}
   * @memberof CheckPaymentStatusResponse
   */
  status?: CheckPaymentStatusResponseStatusEnum;
  /**
   *
   * @type {string}
   * @memberof CheckPaymentStatusResponse
   */
  subscriptionId?: string;
  /**
   *
   * @type {string}
   * @memberof CheckPaymentStatusResponse
   */
  customerEmail?: string;
}

export const CheckPaymentStatusResponseStatusEnum = {
  Complete: 'complete',
  Open: 'open',
  Expired: 'expired',
} as const;

export type CheckPaymentStatusResponseStatusEnum =
  (typeof CheckPaymentStatusResponseStatusEnum)[keyof typeof CheckPaymentStatusResponseStatusEnum];

/**
 *
 * @export
 * @interface CreateCheckoutRequest
 */
export interface CreateCheckoutRequest {
  /**
   *
   * @type {string}
   * @memberof CreateCheckoutRequest
   */
  priceId: string;
}
/**
 *
 * @export
 * @interface CreateCheckoutSessionResponse
 */
export interface CreateCheckoutSessionResponse {
  /**
   *
   * @type {string}
   * @memberof CreateCheckoutSessionResponse
   */
  clientSecret?: string;
}
/**
 *
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
  /**
   *
   * @type {string}
   * @memberof ErrorResponse
   */
  error?: string;
  /**
   *
   * @type {number}
   * @memberof ErrorResponse
   */
  code?: number;
}
/**
 *
 * @export
 * @interface GetAllSubscriptionHistoryPaginatedResponse
 */
export interface GetAllSubscriptionHistoryPaginatedResponse {
  /**
   *
   * @type {boolean}
   * @memberof GetAllSubscriptionHistoryPaginatedResponse
   */
  hasMore?: boolean;
  /**
   *
   * @type {Array<SubscriptionHistoryResponse>}
   * @memberof GetAllSubscriptionHistoryPaginatedResponse
   */
  data?: Array<SubscriptionHistoryResponse>;
}
/**
 *
 * @export
 * @interface Pagination
 */
export interface Pagination {
  /**
   *
   * @type {number}
   * @memberof Pagination
   */
  totalItems?: number;
  /**
   *
   * @type {number}
   * @memberof Pagination
   */
  pageSize?: number;
  /**
   *
   * @type {number}
   * @memberof Pagination
   */
  currentPage?: number;
  /**
   *
   * @type {number}
   * @memberof Pagination
   */
  totalPages?: number;
}
/**
 *
 * @export
 * @interface SubscriptionHistoryResponse
 */
export interface SubscriptionHistoryResponse {
  /**
   *
   * @type {string}
   * @memberof SubscriptionHistoryResponse
   */
  subscriptionId?: string;
  /**
   *
   * @type {string}
   * @memberof SubscriptionHistoryResponse
   */
  invoiceId?: string;
  /**
   *
   * @type {string}
   * @memberof SubscriptionHistoryResponse
   */
  planName?: string;
  /**
   *
   * @type {number}
   * @memberof SubscriptionHistoryResponse
   */
  price?: number;
  /**
   *
   * @type {string}
   * @memberof SubscriptionHistoryResponse
   */
  currency?: string;
  /**
   *
   * @type {string}
   * @memberof SubscriptionHistoryResponse
   */
  billingDate?: string;
  /**
   *
   * @type {string}
   * @memberof SubscriptionHistoryResponse
   */
  status?: SubscriptionHistoryResponseStatusEnum;
  /**
   *
   * @type {string}
   * @memberof SubscriptionHistoryResponse
   */
  downloadUrl?: string;
}

export const SubscriptionHistoryResponseStatusEnum = {
  Active: 'ACTIVE',
  Canceled: 'CANCELED',
  Incomplete: 'INCOMPLETE',
  IncompleteExpired: 'INCOMPLETE_EXPIRED',
  PastDue: 'PAST_DUE',
  Trialing: 'TRIALING',
  Unpaid: 'UNPAID',
} as const;

export type SubscriptionHistoryResponseStatusEnum =
  (typeof SubscriptionHistoryResponseStatusEnum)[keyof typeof SubscriptionHistoryResponseStatusEnum];

/**
 *
 * @export
 * @interface SubscriptionPlanDto
 */
export interface SubscriptionPlanDto {
  /**
   *
   * @type {string}
   * @memberof SubscriptionPlanDto
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof SubscriptionPlanDto
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof SubscriptionPlanDto
   */
  price?: string;
  /**
   *
   * @type {string}
   * @memberof SubscriptionPlanDto
   */
  currency?: string;
  /**
   *
   * @type {string}
   * @memberof SubscriptionPlanDto
   */
  interval?: string;
  /**
   *
   * @type {string}
   * @memberof SubscriptionPlanDto
   */
  description?: string;
  /**
   *
   * @type {boolean}
   * @memberof SubscriptionPlanDto
   */
  recommended?: boolean;
  /**
   *
   * @type {Array<string>}
   * @memberof SubscriptionPlanDto
   */
  features?: Array<string>;
  /**
   *
   * @type {Array<BillingOptionDto>}
   * @memberof SubscriptionPlanDto
   */
  billingOptions?: Array<BillingOptionDto>;
}
/**
 *
 * @export
 * @interface SubscriptionPlansResponse
 */
export interface SubscriptionPlansResponse {
  /**
   *
   * @type {Array<SubscriptionPlanDto>}
   * @memberof SubscriptionPlansResponse
   */
  data?: Array<SubscriptionPlanDto>;
}
/**
 *
 * @export
 * @interface UserSubscriptionPlanResponse
 */
export interface UserSubscriptionPlanResponse {
  /**
   *
   * @type {string}
   * @memberof UserSubscriptionPlanResponse
   */
  planName?: string;
  /**
   *
   * @type {string}
   * @memberof UserSubscriptionPlanResponse
   */
  billingPeriod?: UserSubscriptionPlanResponseBillingPeriodEnum;
  /**
   *
   * @type {number}
   * @memberof UserSubscriptionPlanResponse
   */
  price?: number;
}

export const UserSubscriptionPlanResponseBillingPeriodEnum = {
  Monthly: 'monthly',
  Annually: 'annually',
} as const;

export type UserSubscriptionPlanResponseBillingPeriodEnum =
  (typeof UserSubscriptionPlanResponseBillingPeriodEnum)[keyof typeof UserSubscriptionPlanResponseBillingPeriodEnum];

/**
 * SubscriptionApi - axios parameter creator
 * @export
 */
export const SubscriptionApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Cancel a subscription for a client
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    cancelSubscription: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/subscriptions/cancel`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Check Stripe Checkout Session status
     * @param {CheckPaymentStatusRequest} checkPaymentStatusRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    checkPaymentStatus: async (
      checkPaymentStatusRequest: CheckPaymentStatusRequest,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'checkPaymentStatusRequest' is not null or undefined
      assertParamExists('checkPaymentStatus', 'checkPaymentStatusRequest', checkPaymentStatusRequest);
      const localVarPath = `/api/v1/subscriptions/payment-status`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
      localVarRequestOptions.data = serializeDataIfNeeded(
        checkPaymentStatusRequest,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Create a Stripe Checkout Session
     * @param {CreateCheckoutRequest} createCheckoutRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCheckoutSession: async (
      createCheckoutRequest: CreateCheckoutRequest,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'createCheckoutRequest' is not null or undefined
      assertParamExists('createCheckoutSession', 'createCheckoutRequest', createCheckoutRequest);
      const localVarPath = `/api/v1/subscriptions`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
      localVarRequestOptions.data = serializeDataIfNeeded(createCheckoutRequest, localVarRequestOptions, configuration);

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get current subscription plan for a client
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCurrentPlan: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/subscriptions/current-plan`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get paginated subscription history
     * @param {string} [from] The starting index of subsciption, you should pass last subscription id from the previous page.
     * @param {number} [size] The number of invoices to return.
     * @param {GetSubscriptionHistoryStatusEnum} [status] Filter by subscription status.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSubscriptionHistory: async (
      from?: string,
      size?: number,
      status?: GetSubscriptionHistoryStatusEnum,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/subscriptions/history`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (from !== undefined) {
        localVarQueryParameter['from'] = from;
      }

      if (size !== undefined) {
        localVarQueryParameter['size'] = size;
      }

      if (status !== undefined) {
        localVarQueryParameter['status'] = status;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get available subscription plans
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSubscriptionPlans: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/user/packages/get_all_packages/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * SubscriptionApi - functional programming interface
 * @export
 */
export const SubscriptionApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = SubscriptionApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Cancel a subscription for a client
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async cancelSubscription(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CancelSubscriptionResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.cancelSubscription(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['SubscriptionApi.cancelSubscription']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Check Stripe Checkout Session status
     * @param {CheckPaymentStatusRequest} checkPaymentStatusRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async checkPaymentStatus(
      checkPaymentStatusRequest: CheckPaymentStatusRequest,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CheckPaymentStatusResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.checkPaymentStatus(checkPaymentStatusRequest, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['SubscriptionApi.checkPaymentStatus']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Create a Stripe Checkout Session
     * @param {CreateCheckoutRequest} createCheckoutRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createCheckoutSession(
      createCheckoutRequest: CreateCheckoutRequest,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateCheckoutSessionResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createCheckoutSession(createCheckoutRequest, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['SubscriptionApi.createCheckoutSession']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Get current subscription plan for a client
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getCurrentPlan(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserSubscriptionPlanResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getCurrentPlan(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['SubscriptionApi.getCurrentPlan']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Get paginated subscription history
     * @param {string} [from] The starting index of subsciption, you should pass last subscription id from the previous page.
     * @param {number} [size] The number of invoices to return.
     * @param {GetSubscriptionHistoryStatusEnum} [status] Filter by subscription status.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getSubscriptionHistory(
      from?: string,
      size?: number,
      status?: GetSubscriptionHistoryStatusEnum,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAllSubscriptionHistoryPaginatedResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getSubscriptionHistory(from, size, status, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['SubscriptionApi.getSubscriptionHistory']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Get available subscription plans
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getSubscriptionPlans(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubscriptionPlansResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getSubscriptionPlans(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['SubscriptionApi.getSubscriptionPlans']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * SubscriptionApi - factory interface
 * @export
 */
export const SubscriptionApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = SubscriptionApiFp(configuration);
  return {
    /**
     *
     * @summary Cancel a subscription for a client
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    cancelSubscription(options?: RawAxiosRequestConfig): AxiosPromise<CancelSubscriptionResponse> {
      return localVarFp.cancelSubscription(options).then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Check Stripe Checkout Session status
     * @param {CheckPaymentStatusRequest} checkPaymentStatusRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    checkPaymentStatus(
      checkPaymentStatusRequest: CheckPaymentStatusRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<CheckPaymentStatusResponse> {
      return localVarFp
        .checkPaymentStatus(checkPaymentStatusRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Create a Stripe Checkout Session
     * @param {CreateCheckoutRequest} createCheckoutRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCheckoutSession(
      createCheckoutRequest: CreateCheckoutRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<CreateCheckoutSessionResponse> {
      return localVarFp
        .createCheckoutSession(createCheckoutRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Get current subscription plan for a client
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCurrentPlan(options?: RawAxiosRequestConfig): AxiosPromise<UserSubscriptionPlanResponse> {
      return localVarFp.getCurrentPlan(options).then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Get paginated subscription history
     * @param {string} [from] The starting index of subsciption, you should pass last subscription id from the previous page.
     * @param {number} [size] The number of invoices to return.
     * @param {GetSubscriptionHistoryStatusEnum} [status] Filter by subscription status.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSubscriptionHistory(
      from?: string,
      size?: number,
      status?: GetSubscriptionHistoryStatusEnum,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<GetAllSubscriptionHistoryPaginatedResponse> {
      return localVarFp.getSubscriptionHistory(from, size, status, options).then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Get available subscription plans
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSubscriptionPlans(options?: RawAxiosRequestConfig): AxiosPromise<SubscriptionPlansResponse> {
      return localVarFp.getSubscriptionPlans(options).then((request) => request(axios, basePath));
    },
  };
};

/**
 * SubscriptionApi - object-oriented interface
 * @export
 * @class SubscriptionApi
 * @extends {BaseAPI}
 */
export class SubscriptionApi extends BaseAPI {
  /**
   *
   * @summary Cancel a subscription for a client
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SubscriptionApi
   */
  public cancelSubscription(options?: RawAxiosRequestConfig) {
    return SubscriptionApiFp(this.configuration)
      .cancelSubscription(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Check Stripe Checkout Session status
   * @param {CheckPaymentStatusRequest} checkPaymentStatusRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SubscriptionApi
   */
  public checkPaymentStatus(checkPaymentStatusRequest: CheckPaymentStatusRequest, options?: RawAxiosRequestConfig) {
    return SubscriptionApiFp(this.configuration)
      .checkPaymentStatus(checkPaymentStatusRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Create a Stripe Checkout Session
   * @param {CreateCheckoutRequest} createCheckoutRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SubscriptionApi
   */
  public createCheckoutSession(createCheckoutRequest: CreateCheckoutRequest, options?: RawAxiosRequestConfig) {
    return SubscriptionApiFp(this.configuration)
      .createCheckoutSession(createCheckoutRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Get current subscription plan for a client
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SubscriptionApi
   */
  public getCurrentPlan(options?: RawAxiosRequestConfig) {
    return SubscriptionApiFp(this.configuration)
      .getCurrentPlan(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Get paginated subscription history
   * @param {string} [from] The starting index of subsciption, you should pass last subscription id from the previous page.
   * @param {number} [size] The number of invoices to return.
   * @param {GetSubscriptionHistoryStatusEnum} [status] Filter by subscription status.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SubscriptionApi
   */
  public getSubscriptionHistory(
    from?: string,
    size?: number,
    status?: GetSubscriptionHistoryStatusEnum,
    options?: RawAxiosRequestConfig
  ) {
    return SubscriptionApiFp(this.configuration)
      .getSubscriptionHistory(from, size, status, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Get available subscription plans
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SubscriptionApi
   */
  public getSubscriptionPlans(options?: RawAxiosRequestConfig) {
    return SubscriptionApiFp(this.configuration)
      .getSubscriptionPlans(options)
      .then((request) => request(this.axios, this.basePath));
  }
}

/**
 * @export
 */
export const GetSubscriptionHistoryStatusEnum = {
  Active: 'active',
  Canceled: 'canceled',
  Incomplete: 'incomplete',
  IncompleteExpired: 'incomplete_expired',
  PastDue: 'past_due',
  Trialing: 'trialing',
  Unpaid: 'unpaid',
} as const;
export type GetSubscriptionHistoryStatusEnum =
  (typeof GetSubscriptionHistoryStatusEnum)[keyof typeof GetSubscriptionHistoryStatusEnum];
