/* tslint:disable */
/* eslint-disable */
/**
 * Document API
 * API for managing invoice templates and generating invoice documents
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponse
     */
    'error'?: string;
    /**
     * 
     * @type {number}
     * @memberof ErrorResponse
     */
    'code'?: number;
}
/**
 * 
 * @export
 * @interface GetAllTemplatePaginatedResponse
 */
export interface GetAllTemplatePaginatedResponse {
    /**
     * 
     * @type {Pagination}
     * @memberof GetAllTemplatePaginatedResponse
     */
    'pagination'?: Pagination;
    /**
     * 
     * @type {Array<TemplateResponse>}
     * @memberof GetAllTemplatePaginatedResponse
     */
    'data'?: Array<TemplateResponse>;
}
/**
 * 
 * @export
 * @interface Pagination
 */
export interface Pagination {
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'totalItems'?: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'pageSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'currentPage'?: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'totalPages'?: number;
}
/**
 * 
 * @export
 * @interface TemplateResponse
 */
export interface TemplateResponse {
    /**
     * 
     * @type {string}
     * @memberof TemplateResponse
     */
    'templateId'?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateResponse
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateResponse
     */
    'url'?: string;
}

/**
 * TemplatesApi - axios parameter creator
 * @export
 */
export const TemplatesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get all invoice templates
         * @param {number} [from] Pagination start index
         * @param {number} [size] Number of items to return
         * @param {string} [filter] Filter condition
         * @param {string} [orderBy] Field to order by
         * @param {GetTemplatesDirectionEnum} [direction] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTemplates: async (from?: number, size?: number, filter?: string, orderBy?: string, direction?: GetTemplatesDirectionEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/document/templates`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CSRFHeaderAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-CSRF-TOKEN", configuration)

            if (from !== undefined) {
                localVarQueryParameter['from'] = from;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['orderBy'] = orderBy;
            }

            if (direction !== undefined) {
                localVarQueryParameter['direction'] = direction;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TemplatesApi - functional programming interface
 * @export
 */
export const TemplatesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TemplatesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get all invoice templates
         * @param {number} [from] Pagination start index
         * @param {number} [size] Number of items to return
         * @param {string} [filter] Filter condition
         * @param {string} [orderBy] Field to order by
         * @param {GetTemplatesDirectionEnum} [direction] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTemplates(from?: number, size?: number, filter?: string, orderBy?: string, direction?: GetTemplatesDirectionEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAllTemplatePaginatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTemplates(from, size, filter, orderBy, direction, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TemplatesApi.getTemplates']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TemplatesApi - factory interface
 * @export
 */
export const TemplatesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TemplatesApiFp(configuration)
    return {
        /**
         * 
         * @summary Get all invoice templates
         * @param {TemplatesApiGetTemplatesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTemplates(requestParameters: TemplatesApiGetTemplatesRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<GetAllTemplatePaginatedResponse> {
            return localVarFp.getTemplates(requestParameters.from, requestParameters.size, requestParameters.filter, requestParameters.orderBy, requestParameters.direction, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getTemplates operation in TemplatesApi.
 * @export
 * @interface TemplatesApiGetTemplatesRequest
 */
export interface TemplatesApiGetTemplatesRequest {
    /**
     * Pagination start index
     * @type {number}
     * @memberof TemplatesApiGetTemplates
     */
    readonly from?: number

    /**
     * Number of items to return
     * @type {number}
     * @memberof TemplatesApiGetTemplates
     */
    readonly size?: number

    /**
     * Filter condition
     * @type {string}
     * @memberof TemplatesApiGetTemplates
     */
    readonly filter?: string

    /**
     * Field to order by
     * @type {string}
     * @memberof TemplatesApiGetTemplates
     */
    readonly orderBy?: string

    /**
     * 
     * @type {'ASC' | 'DESC'}
     * @memberof TemplatesApiGetTemplates
     */
    readonly direction?: GetTemplatesDirectionEnum
}

/**
 * TemplatesApi - object-oriented interface
 * @export
 * @class TemplatesApi
 * @extends {BaseAPI}
 */
export class TemplatesApi extends BaseAPI {
    /**
     * 
     * @summary Get all invoice templates
     * @param {TemplatesApiGetTemplatesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApi
     */
    public getTemplates(requestParameters: TemplatesApiGetTemplatesRequest = {}, options?: RawAxiosRequestConfig) {
        return TemplatesApiFp(this.configuration).getTemplates(requestParameters.from, requestParameters.size, requestParameters.filter, requestParameters.orderBy, requestParameters.direction, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const GetTemplatesDirectionEnum = {
    Asc: 'ASC',
    Desc: 'DESC'
} as const;
export type GetTemplatesDirectionEnum = typeof GetTemplatesDirectionEnum[keyof typeof GetTemplatesDirectionEnum];


