/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Invoice API
 * API for fetching invoices with authentication and pagination.
 *
 * The version of the OpenAPI document: 2.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponse
     */
    'error'?: string;
    /**
     * 
     * @type {number}
     * @memberof ErrorResponse
     */
    'code'?: number;
}
/**
 * 
 * @export
 * @interface GenerateInvoiceRequest
 */
export interface GenerateInvoiceRequest {
    /**
     * 
     * @type {string}
     * @memberof GenerateInvoiceRequest
     */
    'invoiceNumber': string;
    /**
     * 
     * @type {string}
     * @memberof GenerateInvoiceRequest
     */
    'invoiceDueDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateInvoiceRequest
     */
    'clientId': string;
    /**
     * 
     * @type {Array<ProductRequest>}
     * @memberof GenerateInvoiceRequest
     */
    'products': Array<ProductRequest>;
    /**
     * 
     * @type {string}
     * @memberof GenerateInvoiceRequest
     */
    'paymentTerms'?: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateInvoiceRequest
     */
    'observations'?: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateInvoiceRequest
     */
    'templateId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateInvoiceRequest
     */
    'kind'?: GenerateInvoiceRequestKindEnum;
    /**
     * 
     * @type {number}
     * @memberof GenerateInvoiceRequest
     */
    'discount'?: number;
    /**
     * 
     * @type {number}
     * @memberof GenerateInvoiceRequest
     */
    'tax'?: number;
}

export const GenerateInvoiceRequestKindEnum = {
    F: 'F',
    E: 'E'
} as const;

export type GenerateInvoiceRequestKindEnum = typeof GenerateInvoiceRequestKindEnum[keyof typeof GenerateInvoiceRequestKindEnum];

/**
 * 
 * @export
 * @interface GeneratedInvoiceResponse
 */
export interface GeneratedInvoiceResponse {
    /**
     * 
     * @type {string}
     * @memberof GeneratedInvoiceResponse
     */
    'documentUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratedInvoiceResponse
     */
    'publicUrl'?: string;
}
/**
 * 
 * @export
 * @interface GetAllInvoicesPaginatedResponse
 */
export interface GetAllInvoicesPaginatedResponse {
    /**
     * 
     * @type {Pagination}
     * @memberof GetAllInvoicesPaginatedResponse
     */
    'pagination'?: Pagination;
    /**
     * 
     * @type {Array<InvoiceResponse>}
     * @memberof GetAllInvoicesPaginatedResponse
     */
    'data'?: Array<InvoiceResponse>;
}
/**
 *
 * @export
 * @interface InvoiceResponse
 */
export interface InvoiceResponse {
    [x: string]: string;
    [x: string]: string;
    [x: string]: string;
    /**
     *
     * @type {string}
     * @memberof InvoiceResponse
     */
    'id'?: string;
    /**
     *
     * @type {string}
     * @memberof InvoiceResponse
     */
    'invoiceId'?: string;
    /**
     *
     * @type {string}
     * @memberof InvoiceResponse
     */
    'invoice_number'?: string;
    /**
     *
     * @type {string}
     * @memberof InvoiceResponse
     */
    'due_date'?: string;
    /**
     *
     * @type {number}
     * @memberof InvoiceResponse
     */
    'total_amount'?: number;
    /**
     *
     * @type {string}
     * @memberof InvoiceResponse
     */
    'serviceName'?: string;
    /**
     *
     * @type {number}
     * @memberof InvoiceResponse
     */
    'servicePrice'?: number;
    /**
     *
     * @type {number}
     * @memberof InvoiceResponse
     */
    'clientView'?: number;
    /**
     *
     * @type {string}
     * @memberof InvoiceResponse
     */
    'clientId'?: string;
    /**
     * The client\'s email address to which invoice can be sent.
     * @type {string}
     * @memberof InvoiceResponse
     */
    'clientEmail'?: string;
    /**
     *
     * @type {string}
     * @memberof InvoiceResponse
     */
    'createdAt'?: string;
    /**
     *
     * @type {string}
     * @memberof InvoiceResponse
     */
    'kind'?: InvoiceResponseKindEnum;
    /**
     *
     * @type {boolean}
     * @memberof InvoiceResponse
     */
    'settled'?: boolean;
    /**
     *
     * @type {string}
     * @memberof InvoiceResponse
     */
    'status'?: InvoiceResponseStatusEnum;
    /**
     *
     * @type {string}
     * @memberof InvoiceResponse
     */
    'documentUrl'?: string;
}

export const InvoiceResponseKindEnum = {
    F: 'F',
    E: 'E'
} as const;

export type InvoiceResponseKindEnum = typeof InvoiceResponseKindEnum[keyof typeof InvoiceResponseKindEnum];
export const InvoiceResponseStatusEnum = {
    Active: 'ACTIVE',
    Canceled: 'CANCELED',
    Inactive: 'INACTIVE'
} as const;

export type InvoiceResponseStatusEnum = typeof InvoiceResponseStatusEnum[keyof typeof InvoiceResponseStatusEnum];

/**
 * 
 * @export
 * @interface Pagination
 */
export interface Pagination {
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'totalItems'?: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'pageSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'currentPage'?: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'totalPages'?: number;
}
/**
 * 
 * @export
 * @interface ProductRequest
 */
export interface ProductRequest {
    /**
     * 
     * @type {string}
     * @memberof ProductRequest
     */
    'productId': string;
    /**
     * 
     * @type {number}
     * @memberof ProductRequest
     */
    'price': number;
    /**
     * 
     * @type {number}
     * @memberof ProductRequest
     */
    'quantity': number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductRequest
     */
    'fees'?: Array<string>;
}
/**
 * 
 * @export
 * @interface SendInvoiceByEmail200Response
 */
export interface SendInvoiceByEmail200Response {
    /**
     * 
     * @type {string}
     * @memberof SendInvoiceByEmail200Response
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface SendInvoiceEmailRequest
 */
export interface SendInvoiceEmailRequest {
    /**
     * The unique identifier of the client.
     * @type {string}
     * @memberof SendInvoiceEmailRequest
     */
    'clientId': string;
    /**
     * The unique identifier of the invoice to send.
     * @type {string}
     * @memberof SendInvoiceEmailRequest
     */
    'invoiceId': string;
    /**
     * Optional message to include in the email.
     * @type {string}
     * @memberof SendInvoiceEmailRequest
     */
    'message': string;
}

/**
 * InvoiceApi - axios parameter creator
 * @export
 */
export const InvoiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Deletes a specific invoice by its unique identifier. Requires authentication.
         * @summary Delete an invoice
         * @param {string} invoiceId The unique identifier of the invoice to delete.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteInvoice: async (invoiceId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'invoiceId' is not null or undefined
            assertParamExists('deleteInvoice', 'invoiceId', invoiceId)
            const localVarPath = `/invoices/invoice/delete_invoice/?invoice_id=${invoiceId}`
                .replace(`{${"invoiceId"}}`, encodeURIComponent(String(invoiceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve a specific invoice in PDF format.
         * @summary Download invoice as PDF
         * @param {string} invoiceId The unique identifier of the invoice.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadInvoice: async (invoiceId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'invoiceId' is not null or undefined
            assertParamExists('downloadInvoice', 'invoiceId', invoiceId)
            const localVarPath = `/api/v1/invoices/document/{invoiceId}`
                .replace(`{${"invoiceId"}}`, encodeURIComponent(String(invoiceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Generate an invoice and send its document
         * @param {GenerateInvoiceRequest} generateInvoiceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateInvoice: async (generateInvoiceRequest: GenerateInvoiceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'generateInvoiceRequest' is not null or undefined
            assertParamExists('generateInvoice', 'generateInvoiceRequest', generateInvoiceRequest)
            const localVarPath = `/invoices/invoice/list_invoices/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(generateInvoiceRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a unique reference string to be used in invoice creation.
         * @summary Generate an invoice reference
         * @param {GenerateInvoiceReferenceKindEnum} [kind] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateInvoiceReference: async (kind?: GenerateInvoiceReferenceKindEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/invoices/references/generate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (kind !== undefined) {
                localVarQueryParameter['kind'] = kind;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve a list of invoices with optional filters, sorting, and pagination. Requests require JWT and Refresh Tokens to be present in cookies.
         * @summary Fetch paginated invoices
         * @param {number} [from] The starting index of the invoices.
         * @param {number} [size] The number of invoices to return.
         * @param {string} [filter] Filter criteria for invoices.
         * @param {GetAllInvoicesOrderByEnum} [orderBy] Field to order invoices by.
         * @param {GetAllInvoicesDirectionEnum} [direction] Sorting direction.
         * @param {GetAllInvoicesKindEnum} [kind] Invoice kind Final (F) or Estimation (E).
         * @param {boolean} [settled] Filter by settlement status of the invoice.
         * @param {GetAllInvoicesStatusEnum} [status] Filter invoices by their status.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
     /**
 * Retrieve a list of invoices with optional filters, sorting, and pagination. 
 * Requests require JWT and Refresh Tokens to be present in cookies.
 * @summary Fetch paginated invoices
 */
getAllInvoices: async (
    from?: number,
    size?: number,
    filter?: string,
    orderBy?: GetAllInvoicesOrderByEnum,
    direction?: GetAllInvoicesDirectionEnum,
    kind?: GetAllInvoicesKindEnum,
    settled?: boolean,
    status?: GetAllInvoicesStatusEnum,
    options: RawAxiosRequestConfig = {}
): Promise<RequestArgs> => {
    const localVarPath = `/invoices/invoice/list_invoices/`;
    const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
    let baseOptions;
    if (configuration) {
        baseOptions = configuration.baseOptions;
    }

    const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
    const localVarHeaderParameter = {} as any;
    const localVarQueryParameter = {} as any;

    if (from !== undefined) localVarQueryParameter['from'] = from;
    if (size !== undefined) localVarQueryParameter['size'] = size;
    if (filter !== undefined) localVarQueryParameter['filter'] = filter;
    if (orderBy !== undefined) localVarQueryParameter['orderBy'] = orderBy;
    if (direction !== undefined) localVarQueryParameter['direction'] = direction;
    if (kind !== undefined) localVarQueryParameter['kind'] = kind;
    if (settled !== undefined) localVarQueryParameter['settled'] = settled;
    if (status !== undefined) localVarQueryParameter['status'] = status;

    setSearchParams(localVarUrlObj, localVarQueryParameter);

    let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
    localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
    };

    return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
    };
},

        /**
         * Sends an existing invoice to the specified client\'s email address with an optional message.
         * @summary Send invoice via email
         * @param {SendInvoiceEmailRequest} sendInvoiceEmailRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendInvoiceByEmail: async (sendInvoiceEmailRequest: SendInvoiceEmailRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sendInvoiceEmailRequest' is not null or undefined
            assertParamExists('sendInvoiceByEmail', 'sendInvoiceEmailRequest', sendInvoiceEmailRequest)
            const localVarPath = `/api/v1/invoices/send-email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sendInvoiceEmailRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InvoiceApi - functional programming interface
 * @export
 */
export const InvoiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InvoiceApiAxiosParamCreator(configuration)
    return {
        /**
         * Deletes a specific invoice by its unique identifier. Requires authentication.
         * @summary Delete an invoice
         * @param {string} invoiceId The unique identifier of the invoice to delete.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteInvoice(invoiceId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteInvoice(invoiceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvoiceApi.deleteInvoice']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve a specific invoice in PDF format.
         * @summary Download invoice as PDF
         * @param {string} invoiceId The unique identifier of the invoice.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async downloadInvoice(invoiceId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.downloadInvoice(invoiceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvoiceApi.downloadInvoice']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Generate an invoice and send its document
         * @param {GenerateInvoiceRequest} generateInvoiceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async generateInvoice(generateInvoiceRequest: GenerateInvoiceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GeneratedInvoiceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.generateInvoice(generateInvoiceRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvoiceApi.generateInvoice']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a unique reference string to be used in invoice creation.
         * @summary Generate an invoice reference
         * @param {GenerateInvoiceReferenceKindEnum} [kind] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async generateInvoiceReference(kind?: GenerateInvoiceReferenceKindEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.generateInvoiceReference(kind, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvoiceApi.generateInvoiceReference']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve a list of invoices with optional filters, sorting, and pagination. Requests require JWT and Refresh Tokens to be present in cookies.
         * @summary Fetch paginated invoices
         * @param {number} [from] The starting index of the invoices.
         * @param {number} [size] The number of invoices to return.
         * @param {string} [filter] Filter criteria for invoices.
         * @param {GetAllInvoicesOrderByEnum} [orderBy] Field to order invoices by.
         * @param {GetAllInvoicesDirectionEnum} [direction] Sorting direction.
         * @param {GetAllInvoicesKindEnum} [kind] Invoice kind Final (F) or Estimation (E).
         * @param {boolean} [settled] Filter by settlement status of the invoice.
         * @param {GetAllInvoicesStatusEnum} [status] Filter invoices by their status.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllInvoices(from?: number, size?: number, filter?: string, orderBy?: GetAllInvoicesOrderByEnum, direction?: GetAllInvoicesDirectionEnum, kind?: GetAllInvoicesKindEnum, settled?: boolean, status?: GetAllInvoicesStatusEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAllInvoicesPaginatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllInvoices(from, size, filter, orderBy, direction, kind, settled, status, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvoiceApi.getAllInvoices']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },

        /**
         * Sends an existing invoice to the specified client\'s email address with an optional message.
         * @summary Send invoice via email
         * @param {SendInvoiceEmailRequest} sendInvoiceEmailRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendInvoiceByEmail(sendInvoiceEmailRequest: SendInvoiceEmailRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SendInvoiceByEmail200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendInvoiceByEmail(sendInvoiceEmailRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvoiceApi.sendInvoiceByEmail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InvoiceApi - factory interface
 * @export
 */
export const InvoiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InvoiceApiFp(configuration)
    return {
        /**
         * Deletes a specific invoice by its unique identifier. Requires authentication.
         * @summary Delete an invoice
         * @param {InvoiceApiDeleteInvoiceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteInvoice(requestParameters: InvoiceApiDeleteInvoiceRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteInvoice(requestParameters.invoiceId, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve a specific invoice in PDF format.
         * @summary Download invoice as PDF
         * @param {InvoiceApiDownloadInvoiceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadInvoice(requestParameters: InvoiceApiDownloadInvoiceRequest, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.downloadInvoice(requestParameters.invoiceId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Generate an invoice and send its document
         * @param {InvoiceApiGenerateInvoiceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateInvoice(requestParameters: InvoiceApiGenerateInvoiceRequest, options?: RawAxiosRequestConfig): AxiosPromise<GeneratedInvoiceResponse> {
            return localVarFp.generateInvoice(requestParameters.generateInvoiceRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a unique reference string to be used in invoice creation.
         * @summary Generate an invoice reference
         * @param {InvoiceApiGenerateInvoiceReferenceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateInvoiceReference(requestParameters: InvoiceApiGenerateInvoiceReferenceRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.generateInvoiceReference(requestParameters.kind, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve a list of invoices with optional filters, sorting, and pagination. Requests require JWT and Refresh Tokens to be present in cookies.
         * @summary Fetch paginated invoices
         * @param {InvoiceApiGetAllInvoicesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllInvoices(requestParameters: InvoiceApiGetAllInvoicesRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<GetAllInvoicesPaginatedResponse> {
            return localVarFp.getAllInvoices(requestParameters.from, requestParameters.size, requestParameters.filter, requestParameters.orderBy, requestParameters.direction, requestParameters.kind, requestParameters.settled, requestParameters.status, options).then((request) => request(axios, basePath));
        },


        /**
         * Sends an existing invoice to the specified client\'s email address with an optional message.
         * @summary Send invoice via email
         * @param {InvoiceApiSendInvoiceByEmailRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendInvoiceByEmail(requestParameters: InvoiceApiSendInvoiceByEmailRequest, options?: RawAxiosRequestConfig): AxiosPromise<SendInvoiceByEmail200Response> {
            return localVarFp.sendInvoiceByEmail(requestParameters.sendInvoiceEmailRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for deleteInvoice operation in InvoiceApi.
 * @export
 * @interface InvoiceApiDeleteInvoiceRequest
 */
export interface InvoiceApiDeleteInvoiceRequest {
    /**
     * The unique identifier of the invoice to delete.
     * @type {string}
     * @memberof InvoiceApiDeleteInvoice
     */
    readonly invoiceId: string
}

/**
 * Request parameters for downloadInvoice operation in InvoiceApi.
 * @export
 * @interface InvoiceApiDownloadInvoiceRequest
 */
export interface InvoiceApiDownloadInvoiceRequest {
    /**
     * The unique identifier of the invoice.
     * @type {string}
     * @memberof InvoiceApiDownloadInvoice
     */
    readonly invoiceId: string
}

/**
 * Request parameters for generateInvoice operation in InvoiceApi.
 * @export
 * @interface InvoiceApiGenerateInvoiceRequest
 */
export interface InvoiceApiGenerateInvoiceRequest {
    /**
     * 
     * @type {GenerateInvoiceRequest}
     * @memberof InvoiceApiGenerateInvoice
     */
    readonly generateInvoiceRequest: GenerateInvoiceRequest
}

/**
 * Request parameters for generateInvoiceReference operation in InvoiceApi.
 * @export
 * @interface InvoiceApiGenerateInvoiceReferenceRequest
 */
export interface InvoiceApiGenerateInvoiceReferenceRequest {
    /**
     * 
     * @type {'F' | 'E'}
     * @memberof InvoiceApiGenerateInvoiceReference
     */
    readonly kind?: GenerateInvoiceReferenceKindEnum
}

/**
 * Request parameters for getAllInvoices operation in InvoiceApi.
 * @export
 * @interface InvoiceApiGetAllInvoicesRequest
 */
export interface InvoiceApiGetAllInvoicesRequest {
    /**
     * The starting index of the invoices.
     * @type {number}
     * @memberof InvoiceApiGetAllInvoices
     */
    readonly from?: number

    /**
     * The number of invoices to return.
     * @type {number}
     * @memberof InvoiceApiGetAllInvoices
     */
    readonly size?: number

    /**
     * Filter criteria for invoices.
     * @type {string}
     * @memberof InvoiceApiGetAllInvoices
     */
    readonly filter?: string

    /**
     * Field to order invoices by.
     * @type {'createdAt' | 'views'}
     * @memberof InvoiceApiGetAllInvoices
     */
    readonly orderBy?: GetAllInvoicesOrderByEnum

    /**
     * Sorting direction.
     * @type {'ASC' | 'DESC'}
     * @memberof InvoiceApiGetAllInvoices
     */
    readonly direction?: GetAllInvoicesDirectionEnum

    /**
     * Invoice kind Final (F) or Estimation (E).
     * @type {'F' | 'E'}
     * @memberof InvoiceApiGetAllInvoices
     */
    readonly kind?: GetAllInvoicesKindEnum

    /**
     * Filter by settlement status of the invoice.
     * @type {boolean}
     * @memberof InvoiceApiGetAllInvoices
     */
    readonly settled?: boolean

    /**
     * Filter invoices by their status.
     * @type {'ACTIVE' | 'EXPIRED' | 'PAID' | 'UNPAID' | 'INACTIVE'}
     * @memberof InvoiceApiGetAllInvoices
     */
    readonly status?: GetAllInvoicesStatusEnum
}

/**
 * Request parameters for sendInvoiceByEmail operation in InvoiceApi.
 * @export
 * @interface InvoiceApiSendInvoiceByEmailRequest
 */
export interface InvoiceApiSendInvoiceByEmailRequest {
    /**
     * 
     * @type {SendInvoiceEmailRequest}
     * @memberof InvoiceApiSendInvoiceByEmail
     */
    readonly sendInvoiceEmailRequest: SendInvoiceEmailRequest
}

/**
 * InvoiceApi - object-oriented interface
 * @export
 * @class InvoiceApi
 * @extends {BaseAPI}
 */
export class InvoiceApi extends BaseAPI {
    /**
     * Deletes a specific invoice by its unique identifier. Requires authentication.
     * @summary Delete an invoice
     * @param {InvoiceApiDeleteInvoiceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoiceApi
     */
    public deleteInvoice(requestParameters: InvoiceApiDeleteInvoiceRequest, options?: RawAxiosRequestConfig) {
        return InvoiceApiFp(this.configuration).deleteInvoice(requestParameters.invoiceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve a specific invoice in PDF format.
     * @summary Download invoice as PDF
     * @param {InvoiceApiDownloadInvoiceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoiceApi
     */
    public downloadInvoice(requestParameters: InvoiceApiDownloadInvoiceRequest, options?: RawAxiosRequestConfig) {
        return InvoiceApiFp(this.configuration).downloadInvoice(requestParameters.invoiceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Generate an invoice and send its document
     * @param {InvoiceApiGenerateInvoiceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoiceApi
     */
    public generateInvoice(requestParameters: InvoiceApiGenerateInvoiceRequest, options?: RawAxiosRequestConfig) {
        return InvoiceApiFp(this.configuration).generateInvoice(requestParameters.generateInvoiceRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a unique reference string to be used in invoice creation.
     * @summary Generate an invoice reference
     * @param {InvoiceApiGenerateInvoiceReferenceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoiceApi
     */
    public generateInvoiceReference(requestParameters: InvoiceApiGenerateInvoiceReferenceRequest = {}, options?: RawAxiosRequestConfig) {
        return InvoiceApiFp(this.configuration).generateInvoiceReference(requestParameters.kind, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve a list of invoices with optional filters, sorting, and pagination. Requests require JWT and Refresh Tokens to be present in cookies.
     * @summary Fetch paginated invoices
     * @param {InvoiceApiGetAllInvoicesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoiceApi
     */
    public getAllInvoices(requestParameters: InvoiceApiGetAllInvoicesRequest = {}, options?: RawAxiosRequestConfig) {
       return InvoiceApiFp(this.configuration)
    .getAllInvoices(
        requestParameters.from,
        requestParameters.size,
        requestParameters.filter,
        requestParameters.orderBy,
        requestParameters.direction,
        requestParameters.kind,
        requestParameters.settled,
        requestParameters.status,
        options
    )
    .then((request) => request(this.axios, this.basePath));

    }

    /**
     * Sends an existing invoice to the specified client\'s email address with an optional message.
     * @summary Send invoice via email
     * @param {InvoiceApiSendInvoiceByEmailRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoiceApi
     */
    public sendInvoiceByEmail(requestParameters: InvoiceApiSendInvoiceByEmailRequest, options?: RawAxiosRequestConfig) {
        return InvoiceApiFp(this.configuration).sendInvoiceByEmail(requestParameters.sendInvoiceEmailRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const GenerateInvoiceReferenceKindEnum = {
    F: 'F',
    E: 'E'
} as const;
export type GenerateInvoiceReferenceKindEnum = typeof GenerateInvoiceReferenceKindEnum[keyof typeof GenerateInvoiceReferenceKindEnum];
/**
 * @export
 */
export const GetAllInvoicesOrderByEnum = {
    CreatedAt: 'createdAt',
    Views: 'views'
} as const;
export type GetAllInvoicesOrderByEnum = typeof GetAllInvoicesOrderByEnum[keyof typeof GetAllInvoicesOrderByEnum];
/**
 * @export
 */
export const GetAllInvoicesDirectionEnum = {
    Asc: 'ASC',
    Desc: 'DESC'
} as const;
export type GetAllInvoicesDirectionEnum = typeof GetAllInvoicesDirectionEnum[keyof typeof GetAllInvoicesDirectionEnum];
/**
 * @export
 */
export const GetAllInvoicesKindEnum = {
    F: 'F',
    E: 'E'
} as const;
export type GetAllInvoicesKindEnum = typeof GetAllInvoicesKindEnum[keyof typeof GetAllInvoicesKindEnum];
/**
 * @export
 */
export const GetAllInvoicesStatusEnum = {
    Active: 'ACTIVE',
    Expired: 'EXPIRED',
    Paid: 'PAID',
    Unpaid: 'UNPAID',
    Inactive: 'INACTIVE'
} as const;
export type GetAllInvoicesStatusEnum = typeof GetAllInvoicesStatusEnum[keyof typeof GetAllInvoicesStatusEnum];


